red mte(@pcmflatten@{
<  '/0 : PCMusagemodelUsageModel@pcmflatten | usageScenario@-@UsageModel@PCMusagemodelUsageModel@pcmflatten : Set{'_LPnI8CHdEd6lJo4DCALHMw} #
    userData@-@UsageModel@PCMusagemodelUsageModel@pcmflatten : Set{mt} > 
<  '/0/@usageScenario_UsageModel.0/@scenarioBehaviour_UsageScenario/@actions_ScenarioBehaviour.2/@inputParameterUsages_EntryLevelSystemCall.0 :
    PCMparameterVariableUsage@pcmflatten | variableCharacterisation@-@VariableUsage@PCMparameterVariableUsage@pcmflatten : Set{'/0/@usageScenario_UsageModel.0/@scenarioBehaviour_UsageScenario/@actions_ScenarioBehaviour.2/@inputParameterUsages_EntryLevelSystemCall.0/@variableCharacterisation_VariableUsage.0} #
    userData@-@VariableUsage@PCMparameterVariableUsage@pcmflatten : null # callAction@-@@-@VariableUsage@PCMparameterVariableUsage@pcmflatten : null #
    synchronisationPoint@-@VariableUsage@PCMparameterVariableUsage@pcmflatten : null # callReturnAction@-@@-@VariableUsage@PCMparameterVariableUsage@pcmflatten :
    null # setVariableAction@-@VariableUsage@PCMparameterVariableUsage@pcmflatten : null #
    specifiedOutputParameterAbstraction@-@expectedExternalOutputs@-@VariableUsage@PCMparameterVariableUsage@pcmflatten : null #
    assemblyContext@-@@-@VariableUsage@PCMparameterVariableUsage@pcmflatten : null # entryLevelSystemCall@-@InputParameterUsage@PCMparameterVariableUsage@pcmflatten
    : '_NC8HwCHdEd6lJo4DCALHMw # entryLevelSystemCall@-@OutputParameterUsage@PCMparameterVariableUsage@pcmflatten : null #
    namedReference@-@@-@VariableUsage@PCMparameterVariableUsage@pcmflatten : '/0/@usageScenario_UsageModel.0/@scenarioBehaviour_UsageScenario/@actions_ScenarioBehaviour.2/@inputParameterUsages_EntryLevelSystemCall.0/@namedReference__VariableUsage > 
<  '/0/@usageScenario_UsageModel.0/@scenarioBehaviour_UsageScenario/@actions_ScenarioBehaviour.2/@inputParameterUsages_EntryLevelSystemCall.0/@namedReference__VariableUsage : STOEXstoexVariableReference@pcmflatten | referenceName@STOEXstoexAbstractNamedReference@pcmflatten : "doA" > 
<  '/0/@usageScenario_UsageModel.0/@scenarioBehaviour_UsageScenario/@actions_ScenarioBehaviour.2/@inputParameterUsages_EntryLevelSystemCall.0/@variableCharacterisation_VariableUsage.0 : PCMparameterVariableCharacterisation@pcmflatten | specification@-@VariableCharacterisation@PCMparameterVariableCharacterisation@pcmflatten : '/0/@usageScenario_UsageModel.0/@scenarioBehaviour_UsageScenario/@actions_ScenarioBehaviour.2/@inputParameterUsages_EntryLevelSystemCall.0/@variableCharacterisation_VariableUsage.0/@specification_VariableCharacterisation # variableUsage@-@VariableCharacterisation@PCMparameterVariableCharacterisation@pcmflatten :
    '/0/@usageScenario_UsageModel.0/@scenarioBehaviour_UsageScenario/@actions_ScenarioBehaviour.2/@inputParameterUsages_EntryLevelSystemCall.0 #
    type@PCMparameterVariableCharacterisation@pcmflatten : VALUE@VariableCharacterisationType@pcmflatten > 
<  '/0/@usageScenario_UsageModel.0/@scenarioBehaviour_UsageScenario/@actions_ScenarioBehaviour.2/@inputParameterUsages_EntryLevelSystemCall.0/@variableCharacterisation_VariableUsage.0/@specification_VariableCharacterisation : PCMcorePCMRandomVariable@pcmflatten |
    closedWorkload@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    passiveResource@-@capacity@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    variableCharacterisation@-@Specification@PCMcorePCMRandomVariable@pcmflatten : '/0/@usageScenario_UsageModel.0/@scenarioBehaviour_UsageScenario/@actions_ScenarioBehaviour.2/@inputParameterUsages_EntryLevelSystemCall.0/@variableCharacterisation_VariableUsage.0 #
    infrastructureCall@-@@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null # resourceCall@-@@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten :
    null # parametricResourceDemand@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    loopAction@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null # guardedBranchTransition@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten :
    null # specifiedExecutionTime@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    eventChannelSinkConnector@-@@-@FilterCondition@PCMcorePCMRandomVariable@pcmflatten : null #
    assemblyEventConnector@-@@-@FilterCondition@PCMcorePCMRandomVariable@pcmflatten : null # loop@-@LoopIteration@PCMcorePCMRandomVariable@pcmflatten : null #
    openWorkload@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null # delay@-@TimeSpecification@PCMcorePCMRandomVariable@pcmflatten : null #
    communicationLinkResourceSpecifcation@-@throughput@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    processingResourceSpecification@-@processingRate@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    communicationLinkResourceSpecification@-@latency@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    specification@STOEXstoexRandomVariable@pcmflatten : "10" > 
<  '/0/@usageScenario_UsageModel.0/@scenarioBehaviour_UsageScenario/@actions_ScenarioBehaviour.3/@timeSpecification_Delay : PCMcorePCMRandomVariable@pcmflatten |
    closedWorkload@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    passiveResource@-@capacity@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    variableCharacterisation@-@Specification@PCMcorePCMRandomVariable@pcmflatten : null #
    infrastructureCall@-@@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null # resourceCall@-@@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten :
    null # parametricResourceDemand@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    loopAction@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null # guardedBranchTransition@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten :
    null # specifiedExecutionTime@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    eventChannelSinkConnector@-@@-@FilterCondition@PCMcorePCMRandomVariable@pcmflatten : null #
    assemblyEventConnector@-@@-@FilterCondition@PCMcorePCMRandomVariable@pcmflatten : null # loop@-@LoopIteration@PCMcorePCMRandomVariable@pcmflatten : null #
    openWorkload@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null # delay@-@TimeSpecification@PCMcorePCMRandomVariable@pcmflatten :
    '_H8BfsA3zEeCgT6LmvPDQdQ # communicationLinkResourceSpecifcation@-@throughput@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    processingResourceSpecification@-@processingRate@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    communicationLinkResourceSpecification@-@latency@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    specification@STOEXstoexRandomVariable@pcmflatten : "1.0" > 
<  '/0/@usageScenario_UsageModel.0/@workload_UsageScenario : PCMusagemodelOpenWorkload@pcmflatten | usageScenario@-@Workload@PCMusagemodelWorkload@pcmflatten :
    '_LPnI8CHdEd6lJo4DCALHMw # interArrivalTime@-@OpenWorkload@PCMusagemodelOpenWorkload@pcmflatten :
    '/0/@usageScenario_UsageModel.0/@workload_UsageScenario/@interArrivalTime_OpenWorkload > 
<  '/0/@usageScenario_UsageModel.0/@workload_UsageScenario/@interArrivalTime_OpenWorkload : PCMcorePCMRandomVariable@pcmflatten |
    closedWorkload@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    passiveResource@-@capacity@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    variableCharacterisation@-@Specification@PCMcorePCMRandomVariable@pcmflatten : null #
    infrastructureCall@-@@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null # resourceCall@-@@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten :
    null # parametricResourceDemand@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    loopAction@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null # guardedBranchTransition@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten :
    null # specifiedExecutionTime@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    eventChannelSinkConnector@-@@-@FilterCondition@PCMcorePCMRandomVariable@pcmflatten : null #
    assemblyEventConnector@-@@-@FilterCondition@PCMcorePCMRandomVariable@pcmflatten : null # loop@-@LoopIteration@PCMcorePCMRandomVariable@pcmflatten : null #
    openWorkload@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : '/0/@usageScenario_UsageModel.0/@workload_UsageScenario #
    delay@-@TimeSpecification@PCMcorePCMRandomVariable@pcmflatten : null #
    communicationLinkResourceSpecifcation@-@throughput@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    processingResourceSpecification@-@processingRate@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    communicationLinkResourceSpecification@-@latency@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    specification@STOEXstoexRandomVariable@pcmflatten : "500.0" > 
<  '/1 : PCMresourcetypeResourceRepository@pcmflatten | resourceInterfaces@-@@-@ResourceRepository@PCMresourcetypeResourceRepository@pcmflatten : Set{
    '_tw_Q8E5CEeCUKeckjJ_n-w ; '_xXv8QE5CEeCUKeckjJ_n-w} # schedulingPolicies@-@@-@ResourceRepository@PCMresourcetypeResourceRepository@pcmflatten : Set{'Delay ;
    'FCFS ; 'ProcessorSharing} # availableResourceTypes@-@ResourceRepository@PCMresourcetypeResourceRepository@pcmflatten : Set{'_BIjHoQ3KEdyouMqirZIhzQ ;
    '_nvHX4KkREdyEA_b89s7q9w ; '_o3sScH2AEdyH8uerKnHYug ; '_oro4gG3fEdy4YaaT-RYrLQ} > 
<  '/2 : PCMresourceenvironmentResourceEnvironment@pcmflatten | linkingResources@-@@-@ResourceEnvironment@PCMresourceenvironmentResourceEnvironment@pcmflatten : Set{
    mt} # resourceContainer@-@ResourceEnvironment@PCMresourceenvironmentResourceEnvironment@pcmflatten : Set{'_B0aZ0CHdEd6lJo4DCALHMw} #
    entityName@PCMentityNamedElement@pcmflatten : "aName" > 
<  '/2/@resourceContainer_ResourceEnvironment.0/@activeResourceSpecifications_ResourceContainer.0/@processingRate_ProcessingResourceSpecification :
    PCMcorePCMRandomVariable@pcmflatten | closedWorkload@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    passiveResource@-@capacity@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    variableCharacterisation@-@Specification@PCMcorePCMRandomVariable@pcmflatten : null #
    infrastructureCall@-@@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null # resourceCall@-@@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten :
    null # parametricResourceDemand@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    loopAction@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null # guardedBranchTransition@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten :
    null # specifiedExecutionTime@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    eventChannelSinkConnector@-@@-@FilterCondition@PCMcorePCMRandomVariable@pcmflatten : null #
    assemblyEventConnector@-@@-@FilterCondition@PCMcorePCMRandomVariable@pcmflatten : null # loop@-@LoopIteration@PCMcorePCMRandomVariable@pcmflatten : null #
    openWorkload@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null # delay@-@TimeSpecification@PCMcorePCMRandomVariable@pcmflatten : null #
    communicationLinkResourceSpecifcation@-@throughput@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    processingResourceSpecification@-@processingRate@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : '_ssJ0QYr-EeG0c6Q1F-wA1Q #
    communicationLinkResourceSpecification@-@latency@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    specification@STOEXstoexRandomVariable@pcmflatten : "1.0810638521955225" > 
<  '/3/@dataTypes__Repository.0 : PCMrepositoryPrimitiveDataType@pcmflatten | repository@-@@-@DataType@PCMrepositoryDataType@pcmflatten : '_Ls3VgHv_Edub45jJKtm_Dg #
    type@PCMrepositoryPrimitiveDataType@pcmflatten : INT@PrimitiveTypeEnum@pcmflatten > 
<  '/3/@dataTypes__Repository.1 : PCMrepositoryPrimitiveDataType@pcmflatten | repository@-@@-@DataType@PCMrepositoryDataType@pcmflatten : '_Ls3VgHv_Edub45jJKtm_Dg #
    type@PCMrepositoryPrimitiveDataType@pcmflatten : STRING@PrimitiveTypeEnum@pcmflatten > 
<  '/3/@dataTypes__Repository.2 : PCMrepositoryPrimitiveDataType@pcmflatten | repository@-@@-@DataType@PCMrepositoryDataType@pcmflatten : '_Ls3VgHv_Edub45jJKtm_Dg #
    type@PCMrepositoryPrimitiveDataType@pcmflatten : BOOL@PrimitiveTypeEnum@pcmflatten > 
<  '/3/@dataTypes__Repository.3 : PCMrepositoryPrimitiveDataType@pcmflatten | repository@-@@-@DataType@PCMrepositoryDataType@pcmflatten : '_Ls3VgHv_Edub45jJKtm_Dg #
    type@PCMrepositoryPrimitiveDataType@pcmflatten : DOUBLE@PrimitiveTypeEnum@pcmflatten > 
<  '/3/@dataTypes__Repository.4 : PCMrepositoryPrimitiveDataType@pcmflatten | repository@-@@-@DataType@PCMrepositoryDataType@pcmflatten : '_Ls3VgHv_Edub45jJKtm_Dg #
    type@PCMrepositoryPrimitiveDataType@pcmflatten : CHAR@PrimitiveTypeEnum@pcmflatten > 
<  '/3/@dataTypes__Repository.5 : PCMrepositoryPrimitiveDataType@pcmflatten | repository@-@@-@DataType@PCMrepositoryDataType@pcmflatten : '_Ls3VgHv_Edub45jJKtm_Dg #
    type@PCMrepositoryPrimitiveDataType@pcmflatten : BYTE@PrimitiveTypeEnum@pcmflatten > 
<  '/4/@components__Repository.0/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.2/@branches_Branch.0/@branchBehaviour_BranchTransition/@steps_Behaviour.2/@resourceDemand_Action.0 : PCMseffperformanceParametricResourceDemand@pcmflatten |
    specification@-@ParametericResourceDemand@PCMseffperformanceParametricResourceDemand@pcmflatten : '/4/@components__Repository.0/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.2/@branches_Branch.0/@branchBehaviour_BranchTransition/@steps_Behaviour.2/@resourceDemand_Action.0/@specification_ParametericResourceDemand # requiredResource@-@ParametricResourceDemand@PCMseffperformanceParametricResourceDemand@pcmflatten : '_oro4gG3fEdy4YaaT-RYrLQ #
    action@-@ParametricResourceDemand@PCMseffperformanceParametricResourceDemand@pcmflatten : '_rl6MwCHbEd62GabW1zGSBw > 
<  '/4/@components__Repository.0/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.2/@branches_Branch.0/@branchBehaviour_BranchTransition/@steps_Behaviour.2/@resourceDemand_Action.0/@specification_ParametericResourceDemand : PCMcorePCMRandomVariable@pcmflatten |
    closedWorkload@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    passiveResource@-@capacity@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    variableCharacterisation@-@Specification@PCMcorePCMRandomVariable@pcmflatten : null #
    infrastructureCall@-@@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null # resourceCall@-@@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten :
    null # parametricResourceDemand@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : '/4/@components__Repository.0/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.2/@branches_Branch.0/@branchBehaviour_BranchTransition/@steps_Behaviour.2/@resourceDemand_Action.0 #
    loopAction@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null # guardedBranchTransition@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten :
    null # specifiedExecutionTime@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    eventChannelSinkConnector@-@@-@FilterCondition@PCMcorePCMRandomVariable@pcmflatten : null #
    assemblyEventConnector@-@@-@FilterCondition@PCMcorePCMRandomVariable@pcmflatten : null # loop@-@LoopIteration@PCMcorePCMRandomVariable@pcmflatten : null #
    openWorkload@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null # delay@-@TimeSpecification@PCMcorePCMRandomVariable@pcmflatten : null #
    communicationLinkResourceSpecifcation@-@throughput@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    processingResourceSpecification@-@processingRate@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    communicationLinkResourceSpecification@-@latency@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    specification@STOEXstoexRandomVariable@pcmflatten : "doA.VALUE * 10" > 
<  '/4/@components__Repository.0/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.2/@branches_Branch.0/@branchBehaviour_BranchTransition/@steps_Behaviour.3/@inputVariableUsages__CallAction.0 : PCMparameterVariableUsage@pcmflatten | variableCharacterisation@-@VariableUsage@PCMparameterVariableUsage@pcmflatten : Set{'/4/@components__Repository.0/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.2/@branches_Branch.0/@branchBehaviour_BranchTransition/@steps_Behaviour.3/@inputVariableUsages__CallAction.0/@variableCharacterisation_VariableUsage.0} # userData@-@VariableUsage@PCMparameterVariableUsage@pcmflatten : null #
    callAction@-@@-@VariableUsage@PCMparameterVariableUsage@pcmflatten : '_VloHcIXQEeSup9fKV6290w #
    synchronisationPoint@-@VariableUsage@PCMparameterVariableUsage@pcmflatten : null # callReturnAction@-@@-@VariableUsage@PCMparameterVariableUsage@pcmflatten :
    null # setVariableAction@-@VariableUsage@PCMparameterVariableUsage@pcmflatten : null #
    specifiedOutputParameterAbstraction@-@expectedExternalOutputs@-@VariableUsage@PCMparameterVariableUsage@pcmflatten : null #
    assemblyContext@-@@-@VariableUsage@PCMparameterVariableUsage@pcmflatten : null # entryLevelSystemCall@-@InputParameterUsage@PCMparameterVariableUsage@pcmflatten
    : null # entryLevelSystemCall@-@OutputParameterUsage@PCMparameterVariableUsage@pcmflatten : null #
    namedReference@-@@-@VariableUsage@PCMparameterVariableUsage@pcmflatten : '/4/@components__Repository.0/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.2/@branches_Branch.0/@branchBehaviour_BranchTransition/@steps_Behaviour.3/@inputVariableUsages__CallAction.0/@namedReference__VariableUsage > 
<  '/4/@components__Repository.0/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.2/@branches_Branch.0/@branchBehaviour_BranchTransition/@steps_Behaviour.3/@inputVariableUsages__CallAction.0/@namedReference__VariableUsage : STOEXstoexVariableReference@pcmflatten |
    referenceName@STOEXstoexAbstractNamedReference@pcmflatten : "foB" > 
<  '/4/@components__Repository.0/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.2/@branches_Branch.0/@branchBehaviour_BranchTransition/@steps_Behaviour.3/@inputVariableUsages__CallAction.0/@variableCharacterisation_VariableUsage.0 : PCMparameterVariableCharacterisation@pcmflatten |
    specification@-@VariableCharacterisation@PCMparameterVariableCharacterisation@pcmflatten : '/4/@components__Repository.0/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.2/@branches_Branch.0/@branchBehaviour_BranchTransition/@steps_Behaviour.3/@inputVariableUsages__CallAction.0/@variableCharacterisation_VariableUsage.0/@specification_VariableCharacterisation # variableUsage@-@VariableCharacterisation@PCMparameterVariableCharacterisation@pcmflatten : '/4/@components__Repository.0/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.2/@branches_Branch.0/@branchBehaviour_BranchTransition/@steps_Behaviour.3/@inputVariableUsages__CallAction.0 # type@PCMparameterVariableCharacterisation@pcmflatten : VALUE@VariableCharacterisationType@pcmflatten > 
<  '/4/@components__Repository.0/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.2/@branches_Branch.0/@branchBehaviour_BranchTransition/@steps_Behaviour.3/@inputVariableUsages__CallAction.0/@variableCharacterisation_VariableUsage.0/@specification_VariableCharacterisation : PCMcorePCMRandomVariable@pcmflatten |
    closedWorkload@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    passiveResource@-@capacity@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    variableCharacterisation@-@Specification@PCMcorePCMRandomVariable@pcmflatten : '/4/@components__Repository.0/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.2/@branches_Branch.0/@branchBehaviour_BranchTransition/@steps_Behaviour.3/@inputVariableUsages__CallAction.0/@variableCharacterisation_VariableUsage.0 #
    infrastructureCall@-@@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null # resourceCall@-@@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten :
    null # parametricResourceDemand@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    loopAction@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null # guardedBranchTransition@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten :
    null # specifiedExecutionTime@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    eventChannelSinkConnector@-@@-@FilterCondition@PCMcorePCMRandomVariable@pcmflatten : null #
    assemblyEventConnector@-@@-@FilterCondition@PCMcorePCMRandomVariable@pcmflatten : null # loop@-@LoopIteration@PCMcorePCMRandomVariable@pcmflatten : null #
    openWorkload@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null # delay@-@TimeSpecification@PCMcorePCMRandomVariable@pcmflatten : null #
    communicationLinkResourceSpecifcation@-@throughput@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    processingResourceSpecification@-@processingRate@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    communicationLinkResourceSpecification@-@latency@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    specification@STOEXstoexRandomVariable@pcmflatten : "doA.VALUE" > 
<  '/4/@components__Repository.0/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.2/@branches_Branch.0/@branchBehaviour_BranchTransition/@steps_Behaviour.3/@returnVariableUsage__CallReturnAction.0 : PCMparameterVariableUsage@pcmflatten | variableCharacterisation@-@VariableUsage@PCMparameterVariableUsage@pcmflatten
    : Set{'/4/@components__Repository.0/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.2/@branches_Branch.0/@branchBehaviour_BranchTransition/@steps_Behaviour.3/@returnVariableUsage__CallReturnAction.0/@variableCharacterisation_VariableUsage.0} # userData@-@VariableUsage@PCMparameterVariableUsage@pcmflatten :
    null # callAction@-@@-@VariableUsage@PCMparameterVariableUsage@pcmflatten : null # synchronisationPoint@-@VariableUsage@PCMparameterVariableUsage@pcmflatten :
    null # callReturnAction@-@@-@VariableUsage@PCMparameterVariableUsage@pcmflatten : '_VloHcIXQEeSup9fKV6290w #
    setVariableAction@-@VariableUsage@PCMparameterVariableUsage@pcmflatten : null #
    specifiedOutputParameterAbstraction@-@expectedExternalOutputs@-@VariableUsage@PCMparameterVariableUsage@pcmflatten : null #
    assemblyContext@-@@-@VariableUsage@PCMparameterVariableUsage@pcmflatten : null # entryLevelSystemCall@-@InputParameterUsage@PCMparameterVariableUsage@pcmflatten
    : null # entryLevelSystemCall@-@OutputParameterUsage@PCMparameterVariableUsage@pcmflatten : null #
    namedReference@-@@-@VariableUsage@PCMparameterVariableUsage@pcmflatten : '/4/@components__Repository.0/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.2/@branches_Branch.0/@branchBehaviour_BranchTransition/@steps_Behaviour.3/@returnVariableUsage__CallReturnAction.0/@namedReference__VariableUsage > 
<  '/4/@components__Repository.0/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.2/@branches_Branch.0/@branchBehaviour_BranchTransition/@steps_Behaviour.3/@returnVariableUsage__CallReturnAction.0/@namedReference__VariableUsage : STOEXstoexVariableReference@pcmflatten |
    referenceName@STOEXstoexAbstractNamedReference@pcmflatten : "RETURN" > 
<  '/4/@components__Repository.0/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.2/@branches_Branch.0/@branchBehaviour_BranchTransition/@steps_Behaviour.3/@returnVariableUsage__CallReturnAction.0/@variableCharacterisation_VariableUsage.0 : PCMparameterVariableCharacterisation@pcmflatten |
    specification@-@VariableCharacterisation@PCMparameterVariableCharacterisation@pcmflatten : '/4/@components__Repository.0/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.2/@branches_Branch.0/@branchBehaviour_BranchTransition/@steps_Behaviour.3/@returnVariableUsage__CallReturnAction.0/@variableCharacterisation_VariableUsage.0/@specification_VariableCharacterisation # variableUsage@-@VariableCharacterisation@PCMparameterVariableCharacterisation@pcmflatten : '/4/@components__Repository.0/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.2/@branches_Branch.0/@branchBehaviour_BranchTransition/@steps_Behaviour.3/@returnVariableUsage__CallReturnAction.0 # type@PCMparameterVariableCharacterisation@pcmflatten : VALUE@VariableCharacterisationType@pcmflatten > 
<  '/4/@components__Repository.0/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.2/@branches_Branch.0/@branchBehaviour_BranchTransition/@steps_Behaviour.3/@returnVariableUsage__CallReturnAction.0/@variableCharacterisation_VariableUsage.0/@specification_VariableCharacterisation : PCMcorePCMRandomVariable@pcmflatten
    | closedWorkload@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    passiveResource@-@capacity@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    variableCharacterisation@-@Specification@PCMcorePCMRandomVariable@pcmflatten : '/4/@components__Repository.0/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.2/@branches_Branch.0/@branchBehaviour_BranchTransition/@steps_Behaviour.3/@returnVariableUsage__CallReturnAction.0/@variableCharacterisation_VariableUsage.0 # infrastructureCall@-@@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null # resourceCall@-@@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten :
    null # parametricResourceDemand@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    loopAction@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null # guardedBranchTransition@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten :
    null # specifiedExecutionTime@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    eventChannelSinkConnector@-@@-@FilterCondition@PCMcorePCMRandomVariable@pcmflatten : null #
    assemblyEventConnector@-@@-@FilterCondition@PCMcorePCMRandomVariable@pcmflatten : null # loop@-@LoopIteration@PCMcorePCMRandomVariable@pcmflatten : null #
    openWorkload@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null # delay@-@TimeSpecification@PCMcorePCMRandomVariable@pcmflatten : null #
    communicationLinkResourceSpecifcation@-@throughput@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    processingResourceSpecification@-@processingRate@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    communicationLinkResourceSpecification@-@latency@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    specification@STOEXstoexRandomVariable@pcmflatten : "RETURN.VALUE" > 
<  '/4/@components__Repository.0/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.2/@branches_Branch.1/@branchBehaviour_BranchTransition/@steps_Behaviour.2/@resourceDemand_Action.0 : PCMseffperformanceParametricResourceDemand@pcmflatten |
    specification@-@ParametericResourceDemand@PCMseffperformanceParametricResourceDemand@pcmflatten : '/4/@components__Repository.0/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.2/@branches_Branch.1/@branchBehaviour_BranchTransition/@steps_Behaviour.2/@resourceDemand_Action.0/@specification_ParametericResourceDemand # requiredResource@-@ParametricResourceDemand@PCMseffperformanceParametricResourceDemand@pcmflatten : '_oro4gG3fEdy4YaaT-RYrLQ #
    action@-@ParametricResourceDemand@PCMseffperformanceParametricResourceDemand@pcmflatten : '_0eyYUCHjEd6ZSMvOJK-6LQ > 
<  '/4/@components__Repository.0/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.2/@branches_Branch.1/@branchBehaviour_BranchTransition/@steps_Behaviour.2/@resourceDemand_Action.0/@specification_ParametericResourceDemand : PCMcorePCMRandomVariable@pcmflatten |
    closedWorkload@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    passiveResource@-@capacity@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    variableCharacterisation@-@Specification@PCMcorePCMRandomVariable@pcmflatten : null #
    infrastructureCall@-@@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null # resourceCall@-@@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten :
    null # parametricResourceDemand@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : '/4/@components__Repository.0/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.2/@branches_Branch.1/@branchBehaviour_BranchTransition/@steps_Behaviour.2/@resourceDemand_Action.0 #
    loopAction@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null # guardedBranchTransition@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten :
    null # specifiedExecutionTime@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    eventChannelSinkConnector@-@@-@FilterCondition@PCMcorePCMRandomVariable@pcmflatten : null #
    assemblyEventConnector@-@@-@FilterCondition@PCMcorePCMRandomVariable@pcmflatten : null # loop@-@LoopIteration@PCMcorePCMRandomVariable@pcmflatten : null #
    openWorkload@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null # delay@-@TimeSpecification@PCMcorePCMRandomVariable@pcmflatten : null #
    communicationLinkResourceSpecifcation@-@throughput@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    processingResourceSpecification@-@processingRate@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    communicationLinkResourceSpecification@-@latency@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    specification@STOEXstoexRandomVariable@pcmflatten : "DoublePDF[ (1.0; 0.25000000) (2.0; 0.50000000) (3.0; 0.25000000) ]" > 
<  '/4/@components__Repository.1/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.2/@bodyBehaviour_Loop/@steps_Behaviour.2/@resourceDemand_Action.0 :
    PCMseffperformanceParametricResourceDemand@pcmflatten | specification@-@ParametericResourceDemand@PCMseffperformanceParametricResourceDemand@pcmflatten : '/4/@components__Repository.1/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.2/@bodyBehaviour_Loop/@steps_Behaviour.2/@resourceDemand_Action.0/@specification_ParametericResourceDemand # requiredResource@-@ParametricResourceDemand@PCMseffperformanceParametricResourceDemand@pcmflatten : '_oro4gG3fEdy4YaaT-RYrLQ #
    action@-@ParametricResourceDemand@PCMseffperformanceParametricResourceDemand@pcmflatten : '_xomfcIXPEeSup9fKV6290w > 
<  '/4/@components__Repository.1/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.2/@bodyBehaviour_Loop/@steps_Behaviour.2/@resourceDemand_Action.0/@specification_ParametericResourceDemand : PCMcorePCMRandomVariable@pcmflatten | closedWorkload@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    passiveResource@-@capacity@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    variableCharacterisation@-@Specification@PCMcorePCMRandomVariable@pcmflatten : null #
    infrastructureCall@-@@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null # resourceCall@-@@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten :
    null # parametricResourceDemand@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten :
    '/4/@components__Repository.1/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.2/@bodyBehaviour_Loop/@steps_Behaviour.2/@resourceDemand_Action.0 #
    loopAction@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null # guardedBranchTransition@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten :
    null # specifiedExecutionTime@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    eventChannelSinkConnector@-@@-@FilterCondition@PCMcorePCMRandomVariable@pcmflatten : null #
    assemblyEventConnector@-@@-@FilterCondition@PCMcorePCMRandomVariable@pcmflatten : null # loop@-@LoopIteration@PCMcorePCMRandomVariable@pcmflatten : null #
    openWorkload@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null # delay@-@TimeSpecification@PCMcorePCMRandomVariable@pcmflatten : null #
    communicationLinkResourceSpecifcation@-@throughput@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    processingResourceSpecification@-@processingRate@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    communicationLinkResourceSpecification@-@latency@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    specification@STOEXstoexRandomVariable@pcmflatten : "2" > 
<  '/4/@components__Repository.1/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.2/@iterationCount_LoopAction : PCMcorePCMRandomVariable@pcmflatten |
    closedWorkload@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    passiveResource@-@capacity@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    variableCharacterisation@-@Specification@PCMcorePCMRandomVariable@pcmflatten : null #
    infrastructureCall@-@@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null # resourceCall@-@@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten :
    null # parametricResourceDemand@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    loopAction@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : '_gJ_TgIXPEeSup9fKV6290w #
    guardedBranchTransition@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    specifiedExecutionTime@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    eventChannelSinkConnector@-@@-@FilterCondition@PCMcorePCMRandomVariable@pcmflatten : null #
    assemblyEventConnector@-@@-@FilterCondition@PCMcorePCMRandomVariable@pcmflatten : null # loop@-@LoopIteration@PCMcorePCMRandomVariable@pcmflatten : null #
    openWorkload@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null # delay@-@TimeSpecification@PCMcorePCMRandomVariable@pcmflatten : null #
    communicationLinkResourceSpecifcation@-@throughput@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    processingResourceSpecification@-@processingRate@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    communicationLinkResourceSpecification@-@latency@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    specification@STOEXstoexRandomVariable@pcmflatten : "5" > 
<  '/4/@components__Repository.1/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.3/@localVariableUsages_SetVariableAction.0 :
    PCMparameterVariableUsage@pcmflatten | variableCharacterisation@-@VariableUsage@PCMparameterVariableUsage@pcmflatten : Set{'/4/@components__Repository.1/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.3/@localVariableUsages_SetVariableAction.0/@variableCharacterisation_VariableUsage.0} #
    userData@-@VariableUsage@PCMparameterVariableUsage@pcmflatten : null # callAction@-@@-@VariableUsage@PCMparameterVariableUsage@pcmflatten : null #
    synchronisationPoint@-@VariableUsage@PCMparameterVariableUsage@pcmflatten : null # callReturnAction@-@@-@VariableUsage@PCMparameterVariableUsage@pcmflatten :
    null # setVariableAction@-@VariableUsage@PCMparameterVariableUsage@pcmflatten : '_tfxzcIXQEeSup9fKV6290w #
    specifiedOutputParameterAbstraction@-@expectedExternalOutputs@-@VariableUsage@PCMparameterVariableUsage@pcmflatten : null #
    assemblyContext@-@@-@VariableUsage@PCMparameterVariableUsage@pcmflatten : null # entryLevelSystemCall@-@InputParameterUsage@PCMparameterVariableUsage@pcmflatten
    : null # entryLevelSystemCall@-@OutputParameterUsage@PCMparameterVariableUsage@pcmflatten : null #
    namedReference@-@@-@VariableUsage@PCMparameterVariableUsage@pcmflatten : '/4/@components__Repository.1/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.3/@localVariableUsages_SetVariableAction.0/@namedReference__VariableUsage > 
<  '/4/@components__Repository.1/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.3/@localVariableUsages_SetVariableAction.0/@namedReference__VariableUsage : STOEXstoexVariableReference@pcmflatten | referenceName@STOEXstoexAbstractNamedReference@pcmflatten : "RETURN" > 
<  '/4/@components__Repository.1/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.3/@localVariableUsages_SetVariableAction.0/@variableCharacterisation_VariableUsage.0 : PCMparameterVariableCharacterisation@pcmflatten | specification@-@VariableCharacterisation@PCMparameterVariableCharacterisation@pcmflatten : '/4/@components__Repository.1/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.3/@localVariableUsages_SetVariableAction.0/@variableCharacterisation_VariableUsage.0/@specification_VariableCharacterisation # variableUsage@-@VariableCharacterisation@PCMparameterVariableCharacterisation@pcmflatten :
    '/4/@components__Repository.1/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.3/@localVariableUsages_SetVariableAction.0 #
    type@PCMparameterVariableCharacterisation@pcmflatten : VALUE@VariableCharacterisationType@pcmflatten > 
<  '/4/@components__Repository.1/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.3/@localVariableUsages_SetVariableAction.0/@variableCharacterisation_VariableUsage.0/@specification_VariableCharacterisation : PCMcorePCMRandomVariable@pcmflatten |
    closedWorkload@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    passiveResource@-@capacity@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    variableCharacterisation@-@Specification@PCMcorePCMRandomVariable@pcmflatten : '/4/@components__Repository.1/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.3/@localVariableUsages_SetVariableAction.0/@variableCharacterisation_VariableUsage.0 #
    infrastructureCall@-@@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null # resourceCall@-@@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten :
    null # parametricResourceDemand@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    loopAction@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null # guardedBranchTransition@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten :
    null # specifiedExecutionTime@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    eventChannelSinkConnector@-@@-@FilterCondition@PCMcorePCMRandomVariable@pcmflatten : null #
    assemblyEventConnector@-@@-@FilterCondition@PCMcorePCMRandomVariable@pcmflatten : null # loop@-@LoopIteration@PCMcorePCMRandomVariable@pcmflatten : null #
    openWorkload@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null # delay@-@TimeSpecification@PCMcorePCMRandomVariable@pcmflatten : null #
    communicationLinkResourceSpecifcation@-@throughput@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    processingResourceSpecification@-@processingRate@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    communicationLinkResourceSpecification@-@latency@-@PCMRandomVariable@PCMcorePCMRandomVariable@pcmflatten : null #
    specification@STOEXstoexRandomVariable@pcmflatten : "foB.VALUE*10" > 
<  '/4/@interfaces__Repository.0/@signatures__OperationInterface.0/@parameters__OperationSignature.0 : PCMrepositoryParameter@pcmflatten |
    dataType@-@@-@Parameter@PCMrepositoryParameter@pcmflatten : '/3/@dataTypes__Repository.0 #
    infrastructureSignature@-@@-@Parameter@PCMrepositoryParameter@pcmflatten : null # operationSignature@-@@-@Parameter@PCMrepositoryParameter@pcmflatten :
    '_KjhikgzkEeCFg86gxKwVPw # eventType@-@@-@Parameter@PCMrepositoryParameter@pcmflatten : null # resourceSignature@-@@-@Parameter@PCMrepositoryParameter@pcmflatten
    : null # parameterName@PCMrepositoryParameter@pcmflatten : "doA" # modifier@-@@-@Parameter@PCMrepositoryParameter@pcmflatten : none@ParameterModifier@pcmflatten
    > 
<  '/4/@interfaces__Repository.1/@signatures__OperationInterface.0/@parameters__OperationSignature.0 : PCMrepositoryParameter@pcmflatten |
    dataType@-@@-@Parameter@PCMrepositoryParameter@pcmflatten : '/3/@dataTypes__Repository.0 #
    infrastructureSignature@-@@-@Parameter@PCMrepositoryParameter@pcmflatten : null # operationSignature@-@@-@Parameter@PCMrepositoryParameter@pcmflatten :
    '_iTDuQIXOEeSup9fKV6290w # eventType@-@@-@Parameter@PCMrepositoryParameter@pcmflatten : null # resourceSignature@-@@-@Parameter@PCMrepositoryParameter@pcmflatten
    : null # parameterName@PCMrepositoryParameter@pcmflatten : "foB" # modifier@-@@-@Parameter@PCMrepositoryParameter@pcmflatten : none@ParameterModifier@pcmflatten
    > 
<  '12345 : PCMseffResourceDemandingSEFF@pcmflatten | abstractLoopAction@-@ResourceDemandingBehaviour@PCMseffResourceDemandingBehaviour@pcmflatten : null #
    abstractBranchTransition@-@ResourceDemandingBehaviour@PCMseffResourceDemandingBehaviour@pcmflatten : null #
    steps@-@Behaviour@PCMseffResourceDemandingBehaviour@pcmflatten : Set{'_qZUd0CHbEd62GabW1zGSBw ; '_qZUd0SHbEd62GabW1zGSBw ; '_tfAiwCHjEd6ZSMvOJK-6LQ} #
    tpOb@PCMseffResourceDemandingBehaviour@pcmflatten : null # rtOb@PCMseffResourceDemandingBehaviour@pcmflatten : null #
    describedService@-@@-@SEFF@PCMseffServiceEffectSpecification@pcmflatten : '_KjhikgzkEeCFg86gxKwVPw #
    basicComponent@-@ServiceEffectSpecification@PCMseffServiceEffectSpecification@pcmflatten : '_os1t4CHbEd62GabW1zGSBw #
    resourceDemandingInternalBehaviours@PCMseffResourceDemandingSEFF@pcmflatten : Set{mt} # seffTypeID@PCMseffServiceEffectSpecification@pcmflatten : "1" #
    id@IDENTIFIERidentifierIdentifier@pcmflatten : "12345" > 
<  '21 : TOKENtokensSEFFToken@pcmflatten | tsOb@TOKENtokensSEFFToken@pcmflatten : '22 # context@TOKENtokensSEFFToken@pcmflatten : Set{
    '/0/@usageScenario_UsageModel.0/@scenarioBehaviour_UsageScenario/@actions_ScenarioBehaviour.2/@inputParameterUsages_EntryLevelSystemCall.0} #
    nestedToken@TOKENtokensSEFFToken@pcmflatten : null # loopToken@TOKENtokensSEFFToken@pcmflatten : null # id@TOKENtokensSEFFToken@pcmflatten : "" #
    completed@TOKENtokensSEFFToken@pcmflatten : false # branchNumber@TOKENtokensSEFFToken@pcmflatten : 11 # branchesProb@TOKENtokensSEFFToken@pcmflatten : Sequence{
    1000 # 0} # prob@TOKENtokensSEFFToken@pcmflatten : 43 > 
<  '22 : ObResponseTime@pcmflatten | tStamp@ObTimeStamp@pcmflatten : 500 # counter@ObResponseTime@pcmflatten : 0 # tTime@ObResponseTime@pcmflatten : 0 #
    rTime@ObResponseTime@pcmflatten : 0.0 # allRT@ObResponseTime@pcmflatten : Sequence{mt-ord} > 
<  '45 : AtomicActionExec@MGBehavior | participants@ActionExec@MGBehavior : Set{'46 ; '47 ; '48 ; '49} # variables@ActionExec@MGBehavior : Set{'50} #
    startingTime@ActionExec@MGBehavior : 500 # endingTime@ActionExec@MGBehavior : null # action@ActionExec@MGBehavior : "OpenWorkloadSpec" #
    maxTimer@ActionExec@MGBehavior : 500 # minTimer@AtomicActionExec@MGBehavior : 500 # executionTime@AtomicActionExec@MGBehavior : 0 #
    status@AtomicActionExec@MGBehavior : unfinished@ActionStatus@MGBehavior > 
<  '46 : ObjectRole@MGBehavior | actualObject@ObjectRole@MGBehavior : '_LPwS4SHdEd6lJo4DCALHMw # role@ObjectRole@MGBehavior : "start" > 
<  '47 : ObjectRole@MGBehavior | actualObject@ObjectRole@MGBehavior : '/0/@usageScenario_UsageModel.0/@workload_UsageScenario # role@ObjectRole@MGBehavior : "ow" > 
<  '48 : ObjectRole@MGBehavior | actualObject@ObjectRole@MGBehavior : '_LPnI8CHdEd6lJo4DCALHMw # role@ObjectRole@MGBehavior : "usSc" > 
<  '49 : ObjectRole@MGBehavior | actualObject@ObjectRole@MGBehavior : '_LPwS4CHdEd6lJo4DCALHMw # role@ObjectRole@MGBehavior : "scBeh" > 
<  '50 : Variable@MGBehavior | name@Variable@MGBehavior : "owRate" # value@Variable@MGBehavior : 500 > 
<  '6 : ObTimeStamp@pcmflatten | tStamp@ObTimeStamp@pcmflatten : 500 > 
<  '61 : AtomicActionExec@MGBehavior | participants@ActionExec@MGBehavior : Set{'62 ; '63 ; '64 ; '65 ; '66} # variables@ActionExec@MGBehavior : Set{'67} #
    startingTime@ActionExec@MGBehavior : 500 # endingTime@ActionExec@MGBehavior : null # action@ActionExec@MGBehavior : "InternalActionSEFF" #
    maxTimer@ActionExec@MGBehavior : 93 # minTimer@AtomicActionExec@MGBehavior : 93 # executionTime@AtomicActionExec@MGBehavior : 0 #
    status@AtomicActionExec@MGBehavior : unfinished@ActionStatus@MGBehavior > 
<  '62 : ObjectRole@MGBehavior | actualObject@ObjectRole@MGBehavior : '_rl6MwCHbEd62GabW1zGSBw # role@ObjectRole@MGBehavior : "IA" > 
<  '63 : ObjectRole@MGBehavior | actualObject@ObjectRole@MGBehavior : '21 # role@ObjectRole@MGBehavior : "t" > 
<  '64 : ObjectRole@MGBehavior | actualObject@ObjectRole@MGBehavior : '/4/@components__Repository.0/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.2/@branches_Branch.0/@branchBehaviour_BranchTransition/@steps_Behaviour.2/@resourceDemand_Action.0 # role@ObjectRole@MGBehavior : "PRD" > 
<  '65 : ObjectRole@MGBehavior | actualObject@ObjectRole@MGBehavior : '_oro4gG3fEdy4YaaT-RYrLQ # role@ObjectRole@MGBehavior : "PRT" > 
<  '66 : ObjectRole@MGBehavior | actualObject@ObjectRole@MGBehavior : '_ssJ0QYr-EeG0c6Q1F-wA1Q # role@ObjectRole@MGBehavior : "PRS" > 
<  '67 : Variable@MGBehavior | name@Variable@MGBehavior : "rTime" # value@Variable@MGBehavior : 93 > 
<  '7 : TOKENtokensUSToken@pcmflatten | tsOb@TOKENtokensUSToken@pcmflatten : '6 # cToken@TOKENtokensUSToken@pcmflatten : '21 # id@TOKENtokensUSToken@pcmflatten : ""
    # completed@TOKENtokensUSToken@pcmflatten : false # branchNumber@TOKENtokensUSToken@pcmflatten : 0 # branchesProb@TOKENtokensUSToken@pcmflatten : Sequence{
    mt-ord} # prob@TOKENtokensUSToken@pcmflatten : 0 > 
<  'Delay : PCMresourcetypeSchedulingPolicy@pcmflatten | resourceRepository@-@@-@SchedulingPolicy@PCMresourcetypeSchedulingPolicy@pcmflatten : '/1 #
    entityName@PCMentityNamedElement@pcmflatten : "Delay" # id@IDENTIFIERidentifierIdentifier@pcmflatten : "Delay" > 
<  'FCFS : PCMresourcetypeSchedulingPolicy@pcmflatten | resourceRepository@-@@-@SchedulingPolicy@PCMresourcetypeSchedulingPolicy@pcmflatten : '/1 #
    entityName@PCMentityNamedElement@pcmflatten : "First-Come-First-Serve" # id@IDENTIFIERidentifierIdentifier@pcmflatten : "FCFS" > 
<  'ProcessorSharing : PCMresourcetypeSchedulingPolicy@pcmflatten | resourceRepository@-@@-@SchedulingPolicy@PCMresourcetypeSchedulingPolicy@pcmflatten : '/1 #
    entityName@PCMentityNamedElement@pcmflatten : "Processor Sharing" # id@IDENTIFIERidentifierIdentifier@pcmflatten : "ProcessorSharing" > 
<  '_-r1fUCHcEd6lJo4DCALHMw : PCMrepositoryOperationProvidedRole@pcmflatten | providingEntity@-@ProvidedRole@PCMrepositoryProvidedRole@pcmflatten :
    '_84D0kCHcEd6lJo4DCALHMw # providedInterface@-@@-@OperationProvidedRole@PCMrepositoryOperationProvidedRole@pcmflatten : '_n7g-oCHbEd62GabW1zGSBw #
    entityName@PCMentityNamedElement@pcmflatten : "Provided_AnInterface" # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_-r1fUCHcEd6lJo4DCALHMw" > 
<  '_0eyYUCHjEd6ZSMvOJK-6LQ : PCMseffInternalAction@pcmflatten | resourceDemand@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{'/4/@components__Repository.0/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.2/@branches_Branch.1/@branchBehaviour_BranchTransition/@steps_Behaviour.2/@resourceDemand_Action.0} # infrastructureCall@-@@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} #
    resourceCall@-@@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} # predecessor@-@AbstractAction@PCMseffAbstractAction@pcmflatten :
    '_zcoXwSHjEd6ZSMvOJK-6LQ # successor@-@AbstractAction@PCMseffAbstractAction@pcmflatten : '_zcoXwiHjEd6ZSMvOJK-6LQ #
    resourceDemandingBehaviour@-@AbstractAction@PCMseffAbstractAction@pcmflatten : '_ssGw-Yr-EeG0c6Q1F-wA1Q # token@PCMseffAbstractAction@pcmflatten : OrderedSet{
    mt-ord} # internalFailureOccurrenceDescriptions@-@@-@InternalAction@PCMseffInternalAction@pcmflatten : Set{mt} # queue@PCMseffInternalAction@pcmflatten :
    Sequence{mt-ord} # entityName@PCMentityNamedElement@pcmflatten : "computeMore" # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_0eyYUCHjEd6ZSMvOJK-6LQ" > 
<  '_84D0kCHcEd6lJo4DCALHMw : PCMsystemSystem@pcmflatten | providedRoles@-@InterfaceProvidingEntity@PCMentityInterfaceProvidingEntity@pcmflatten : Set{
    '_-r1fUCHcEd6lJo4DCALHMw} # requiredRoles@-@InterfaceRequiringEntity@PCMentityInterfaceRequiringEntity@pcmflatten : Set{mt} #
    resourceRequiredRoles@-@@-@ResourceInterfaceRequiringEntity@PCMentityResourceInterfaceRequiringEntity@pcmflatten : Set{mt} #
    assemblyContexts@-@@-@ComposedStructure@PCMcompositionComposedStructure@pcmflatten : Set{'_9c3KwCHcEd6lJo4DCALHMw ; '_E17P8IXQEeSup9fKV6290w} #
    resourceRequiredDelegationConnectors@-@ComposedStructure@PCMcompositionComposedStructure@pcmflatten : Set{mt} #
    eventChannel@-@@-@ComposedStructure@PCMcompositionComposedStructure@pcmflatten : Set{mt} #
    connectors@-@@-@ComposedStructure@PCMcompositionComposedStructure@pcmflatten : Set{'_G9gngIXQEeSup9fKV6290w ; '__VHF0CHcEd6lJo4DCALHMw} #
    qosAnnotations@-@System@PCMsystemSystem@pcmflatten : Set{mt} # entityName@PCMentityNamedElement@pcmflatten : "defaultSystem" #
    id@IDENTIFIERidentifierIdentifier@pcmflatten : "_84D0kCHcEd6lJo4DCALHMw" > 
<  '_9c3KwCHcEd6lJo4DCALHMw : PCMcompositionAssemblyContext@pcmflatten | parentStructure@-@@-@AssemblyContext@PCMcompositionAssemblyContext@pcmflatten :
    '_84D0kCHcEd6lJo4DCALHMw # encapsulatedComponent@-@@-@AssemblyContext@PCMcompositionAssemblyContext@pcmflatten : '_os1t4CHbEd62GabW1zGSBw #
    configParameterUsages@-@@-@AssemblyContext@PCMcompositionAssemblyContext@pcmflatten : Set{mt} # entityName@PCMentityNamedElement@pcmflatten :
    "Assembly_AComponent <AComponent>" # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_9c3KwCHcEd6lJo4DCALHMw" > 
<  '_B0aZ0CHdEd6lJo4DCALHMw : PCMresourceenvironmentResourceContainer@pcmflatten |
    activeResourceSpecifications@-@ResourceContainer@PCMresourceenvironmentResourceContainer@pcmflatten : Set{'_ssJ0QYr-EeG0c6Q1F-wA1Q} #
    resourceEnvironment@-@ResourceContainer@PCMresourceenvironmentResourceContainer@pcmflatten : '/2 #
    nestedResourceContainers@-@@-@ResourceContainer@PCMresourceenvironmentResourceContainer@pcmflatten : Set{mt} #
    parentResourceContainer@-@@-@ResourceContainer@PCMresourceenvironmentResourceContainer@pcmflatten : null # entityName@PCMentityNamedElement@pcmflatten :
    "appserver" # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_B0aZ0CHdEd6lJo4DCALHMw" > 
<  '_BIjHoQ3KEdyouMqirZIhzQ : PCMresourcetypeProcessingResourceType@pcmflatten |
    resourceProvidedRoles@-@@-@ResourceInterfaceProvidingEntity@PCMentityResourceInterfaceProvidingEntity@pcmflatten : Set{'_tCR8kE5dEeCg1tUg4V9tRw} #
    hardwareInducedFailureType@-@@-@ProcessingResourceType@PCMresourcetypeProcessingResourceType@pcmflatten : null #
    resourceRepository@-@ResourceType@PCMresourcetypeResourceType@pcmflatten : '/1 # unit@UNITSunitsUnitCarryingElement@pcmflatten : null #
    entityName@PCMentityNamedElement@pcmflatten : "HDD" # unitSpecification@UNITSunitsUnitCarryingElement@pcmflatten : "byte per second" #
    id@IDENTIFIERidentifierIdentifier@pcmflatten : "_BIjHoQ3KEdyouMqirZIhzQ" > 
<  '_E17P8IXQEeSup9fKV6290w : PCMcompositionAssemblyContext@pcmflatten | parentStructure@-@@-@AssemblyContext@PCMcompositionAssemblyContext@pcmflatten :
    '_84D0kCHcEd6lJo4DCALHMw # encapsulatedComponent@-@@-@AssemblyContext@PCMcompositionAssemblyContext@pcmflatten : '_Rv0lcIXOEeSup9fKV6290w #
    configParameterUsages@-@@-@AssemblyContext@PCMcompositionAssemblyContext@pcmflatten : Set{mt} # entityName@PCMentityNamedElement@pcmflatten :
    "Assembly_BComponent <BComponent>" # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_E17P8IXQEeSup9fKV6290w" > 
<  '_G9gngIXQEeSup9fKV6290w : PCMcompositionAssemblyConnector@pcmflatten | parentStructure@-@@-@Connector@PCMcompositionConnector@pcmflatten :
    '_84D0kCHcEd6lJo4DCALHMw # requiringAssemblyContext@-@AssemblyConnector@PCMcompositionAssemblyConnector@pcmflatten : '_9c3KwCHcEd6lJo4DCALHMw #
    providingAssemblyContext@-@AssemblyConnector@PCMcompositionAssemblyConnector@pcmflatten : '_E17P8IXQEeSup9fKV6290w #
    providedRole@-@AssemblyConnector@PCMcompositionAssemblyConnector@pcmflatten : '_mHheYIXOEeSup9fKV6290w #
    requiredRole@-@AssemblyConnector@PCMcompositionAssemblyConnector@pcmflatten : '_oKe0oIXOEeSup9fKV6290w # entityName@PCMentityNamedElement@pcmflatten :
    "Connector Assembly_AComponent <AComponent> -> Assembly_BComponent <BComponent>" # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_G9gngIXQEeSup9fKV6290w" > 
<  '_H8BfsA3zEeCgT6LmvPDQdQ : PCMusagemodelDelay@pcmflatten | successor@PCMusagemodelAbstractUserAction@pcmflatten : '_LPwS4iHdEd6lJo4DCALHMw #
    predecessor@PCMusagemodelAbstractUserAction@pcmflatten : '_NC8HwCHdEd6lJo4DCALHMw #
    scenarioBehaviour@-@AbstractUserAction@PCMusagemodelAbstractUserAction@pcmflatten : '_LPwS4CHdEd6lJo4DCALHMw # token@PCMusagemodelAbstractUserAction@pcmflatten :
    OrderedSet{mt-ord} # timeSpecification@-@Delay@PCMusagemodelDelay@pcmflatten :
    '/0/@usageScenario_UsageModel.0/@scenarioBehaviour_UsageScenario/@actions_ScenarioBehaviour.3/@timeSpecification_Delay #
    entityName@PCMentityNamedElement@pcmflatten : "aName" # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_H8BfsA3zEeCgT6LmvPDQdQ" > 
<  '_JiPBICHdEd6lJo4DCALHMw : PCMallocationAllocation@pcmflatten | targetResourceEnvironment@-@Allocation@PCMallocationAllocation@pcmflatten : '/2 #
    system@-@Allocation@PCMallocationAllocation@pcmflatten : '_84D0kCHcEd6lJo4DCALHMw # allocationContexts@-@Allocation@PCMallocationAllocation@pcmflatten : Set{
    '_KCkHACHdEd6lJo4DCALHMw ; '_ZOKCcIXSEeSup9fKV6290w} # entityName@PCMentityNamedElement@pcmflatten : "defaultAllocation" #
    id@IDENTIFIERidentifierIdentifier@pcmflatten : "_JiPBICHdEd6lJo4DCALHMw" > 
<  '_KCkHACHdEd6lJo4DCALHMw : PCMallocationAllocationContext@pcmflatten | resourceContainer@-@AllocationContext@PCMallocationAllocationContext@pcmflatten :
    '_B0aZ0CHdEd6lJo4DCALHMw # assemblyContext@-@AllocationContext@PCMallocationAllocationContext@pcmflatten : '_9c3KwCHcEd6lJo4DCALHMw #
    allocation@-@AllocationContext@PCMallocationAllocationContext@pcmflatten : '_JiPBICHdEd6lJo4DCALHMw #
    eventChannel@-@@-@AllocationContext@PCMallocationAllocationContext@pcmflatten : null # entityName@PCMentityNamedElement@pcmflatten :
    "Allocation_Assembly_AComponent <AComponent> <AComponent>" # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_KCkHACHdEd6lJo4DCALHMw" > 
<  '_KjhikgzkEeCFg86gxKwVPw : PCMrepositoryOperationSignature@pcmflatten | exceptions@-@@-@Signature@PCMrepositorySignature@pcmflatten : Set{mt} #
    failureType@PCMrepositorySignature@pcmflatten : Set{mt} # interface@-@@-@OperationSignature@PCMrepositoryOperationSignature@pcmflatten : '_n7g-oCHbEd62GabW1zGSBw
    # parameters@-@@-@OperationSignature@PCMrepositoryOperationSignature@pcmflatten : OrderedSet{
    '/4/@interfaces__Repository.0/@signatures__OperationInterface.0/@parameters__OperationSignature.0} #
    returnType@-@@-@OperationSignature@PCMrepositoryOperationSignature@pcmflatten : '/3/@dataTypes__Repository.0 # entityName@PCMentityNamedElement@pcmflatten : "do"
    # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_KjhikgzkEeCFg86gxKwVPw" > 
<  '_LPnI8CHdEd6lJo4DCALHMw : PCMusagemodelUsageScenario@pcmflatten | usageModel@-@UsageScenario@PCMusagemodelUsageScenario@pcmflatten : '/0 #
    scenarioBehaviour@-@UsageScenario@PCMusagemodelUsageScenario@pcmflatten : '_LPwS4CHdEd6lJo4DCALHMw #
    workload@-@UsageScenario@PCMusagemodelUsageScenario@pcmflatten : '/0/@usageScenario_UsageModel.0/@workload_UsageScenario #
    entityName@PCMentityNamedElement@pcmflatten : "defaultUsageScenario" # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_LPnI8CHdEd6lJo4DCALHMw" > 
<  '_LPwS4CHdEd6lJo4DCALHMw : PCMusagemodelScenarioBehaviour@pcmflatten | usageScenario@-@SenarioBehaviour@PCMusagemodelScenarioBehaviour@pcmflatten :
    '_LPnI8CHdEd6lJo4DCALHMw # branchTransition@-@ScenarioBehaviour@PCMusagemodelScenarioBehaviour@pcmflatten : null #
    loop@-@ScenarioBehaviour@PCMusagemodelScenarioBehaviour@pcmflatten : null # actions@-@ScenarioBehaviour@PCMusagemodelScenarioBehaviour@pcmflatten : Set{
    '_H8BfsA3zEeCgT6LmvPDQdQ ; '_LPwS4SHdEd6lJo4DCALHMw ; '_LPwS4iHdEd6lJo4DCALHMw ; '_NC8HwCHdEd6lJo4DCALHMw} # rtOb@PCMusagemodelScenarioBehaviour@pcmflatten :
    null # tpOb@PCMusagemodelScenarioBehaviour@pcmflatten : null # entityName@PCMentityNamedElement@pcmflatten : "defaultUsageScenarioBehaviour" #
    id@IDENTIFIERidentifierIdentifier@pcmflatten : "_LPwS4CHdEd6lJo4DCALHMw" > 
<  '_LPwS4SHdEd6lJo4DCALHMw : PCMusagemodelStart@pcmflatten | successor@PCMusagemodelAbstractUserAction@pcmflatten : '_NC8HwCHdEd6lJo4DCALHMw #
    predecessor@PCMusagemodelAbstractUserAction@pcmflatten : null # scenarioBehaviour@-@AbstractUserAction@PCMusagemodelAbstractUserAction@pcmflatten :
    '_LPwS4CHdEd6lJo4DCALHMw # token@PCMusagemodelAbstractUserAction@pcmflatten : OrderedSet{mt-ord} # entityName@PCMentityNamedElement@pcmflatten : "aName" #
    id@IDENTIFIERidentifierIdentifier@pcmflatten : "_LPwS4SHdEd6lJo4DCALHMw" > 
<  '_LPwS4iHdEd6lJo4DCALHMw : PCMusagemodelStop@pcmflatten | successor@PCMusagemodelAbstractUserAction@pcmflatten : null #
    predecessor@PCMusagemodelAbstractUserAction@pcmflatten : '_H8BfsA3zEeCgT6LmvPDQdQ #
    scenarioBehaviour@-@AbstractUserAction@PCMusagemodelAbstractUserAction@pcmflatten : '_LPwS4CHdEd6lJo4DCALHMw # token@PCMusagemodelAbstractUserAction@pcmflatten :
    OrderedSet{mt-ord} # entityName@PCMentityNamedElement@pcmflatten : "aName" # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_LPwS4iHdEd6lJo4DCALHMw" > 
<  '_Ls3VgHv_Edub45jJKtm_Dg : PCMrepositoryRepository@pcmflatten | components@-@@-@Repository@PCMrepositoryRepository@pcmflatten : Set{mt} #
    interfaces@-@@-@Repository@PCMrepositoryRepository@pcmflatten : Set{mt} # failureTypes@-@@-@Repository@PCMrepositoryRepository@pcmflatten : Set{mt} #
    dataTypes@-@@-@Repository@PCMrepositoryRepository@pcmflatten : Set{'/3/@dataTypes__Repository.0 ; '/3/@dataTypes__Repository.1 ; '/3/@dataTypes__Repository.2 ;
    '/3/@dataTypes__Repository.3 ; '/3/@dataTypes__Repository.4 ; '/3/@dataTypes__Repository.5} # entityName@PCMentityNamedElement@pcmflatten : "PrimitiveDataTypes"
    # repositoryDescription@PCMrepositoryRepository@pcmflatten : "" # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_Ls3VgHv_Edub45jJKtm_Dg" > 
<  '_NC8HwCHdEd6lJo4DCALHMw : PCMusagemodelEntryLevelSystemCall@pcmflatten | providedRole@-@EntryLevelSystemCall@PCMusagemodelEntryLevelSystemCall@pcmflatten :
    '_-r1fUCHcEd6lJo4DCALHMw # operationSignature@-@@-@EntryLevelSystemCall@PCMusagemodelEntryLevelSystemCall@pcmflatten : '_KjhikgzkEeCFg86gxKwVPw #
    outputParameterUsages@-@EntryLevelSystemCall@PCMusagemodelEntryLevelSystemCall@pcmflatten : Set{mt} #
    inputParameterUsages@-@EntryLevelSystemCall@PCMusagemodelEntryLevelSystemCall@pcmflatten : Set{
    '/0/@usageScenario_UsageModel.0/@scenarioBehaviour_UsageScenario/@actions_ScenarioBehaviour.2/@inputParameterUsages_EntryLevelSystemCall.0} #
    successor@PCMusagemodelAbstractUserAction@pcmflatten : '_H8BfsA3zEeCgT6LmvPDQdQ # predecessor@PCMusagemodelAbstractUserAction@pcmflatten :
    '_LPwS4SHdEd6lJo4DCALHMw # scenarioBehaviour@-@AbstractUserAction@PCMusagemodelAbstractUserAction@pcmflatten : '_LPwS4CHdEd6lJo4DCALHMw #
    token@PCMusagemodelAbstractUserAction@pcmflatten : OrderedSet{'7} # entityName@PCMentityNamedElement@pcmflatten : "aName" #
    priority@PCMusagemodelEntryLevelSystemCall@pcmflatten : 0 # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_NC8HwCHdEd6lJo4DCALHMw" > 
<  '_Rv0lcIXOEeSup9fKV6290w : PCMrepositoryBasicComponent@pcmflatten | providedRoles@-@InterfaceProvidingEntity@PCMentityInterfaceProvidingEntity@pcmflatten : Set{
    '_mHheYIXOEeSup9fKV6290w} # requiredRoles@-@InterfaceRequiringEntity@PCMentityInterfaceRequiringEntity@pcmflatten : Set{mt} #
    resourceRequiredRoles@-@@-@ResourceInterfaceRequiringEntity@PCMentityResourceInterfaceRequiringEntity@pcmflatten : Set{mt} #
    serviceEffectSpecifications@-@@-@BasicComponent@PCMrepositoryBasicComponent@pcmflatten : Set{'_mHj6oIXOEeSup9fKV6290w} #
    passiveResource@-@BasicComponent@PCMrepositoryBasicComponent@pcmflatten : Set{mt} #
    parentCompleteComponentTypes@PCMrepositoryImplementationComponentType@pcmflatten : Set{mt} #
    componentParameterUsage@-@ImplementationComponentType@PCMrepositoryImplementationComponentType@pcmflatten : Set{mt} #
    repository@-@@-@RepositoryComponent@PCMrepositoryRepositoryComponent@pcmflatten : '_dqFLECHbEd6tG9VclJz3cw # entityName@PCMentityNamedElement@pcmflatten :
    "BComponent" # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_Rv0lcIXOEeSup9fKV6290w" > 
<  '_VloHcIXQEeSup9fKV6290w : PCMseffExternalCallAction@pcmflatten | predecessor@-@AbstractAction@PCMseffAbstractAction@pcmflatten : '_rl6MwCHbEd62GabW1zGSBw #
    successor@-@AbstractAction@PCMseffAbstractAction@pcmflatten : '_vN34UiHjEd6ZSMvOJK-6LQ #
    resourceDemandingBehaviour@-@AbstractAction@PCMseffAbstractAction@pcmflatten : '_ssGw84r-EeG0c6Q1F-wA1Q # token@PCMseffAbstractAction@pcmflatten : OrderedSet{
    mt-ord} # inputVariableUsages@-@@-@CallAction@PCMseffCallAction@pcmflatten : Set{'/4/@components__Repository.0/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.2/@branches_Branch.0/@branchBehaviour_BranchTransition/@steps_Behaviour.3/@inputVariableUsages__CallAction.0} #
    calledService@-@ExternalService@PCMseffExternalCallAction@pcmflatten : '_iTDuQIXOEeSup9fKV6290w # role@-@ExternalService@PCMseffExternalCallAction@pcmflatten :
    '_oKe0oIXOEeSup9fKV6290w # returnVariableUsage@-@@-@CallReturnAction@PCMseffCallReturnAction@pcmflatten : Set{'/4/@components__Repository.0/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.2/@branches_Branch.0/@branchBehaviour_BranchTransition/@steps_Behaviour.3/@returnVariableUsage__CallReturnAction.0} #
    failureTypes@-@FailureHandlingEntity@PCMseff@-@reliabilityFailureHandlingEntity@pcmflatten : Set{mt} # entityName@PCMentityNamedElement@pcmflatten : "aName" #
    retryCount@PCMseffExternalCallAction@pcmflatten : 0 # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_VloHcIXQEeSup9fKV6290w" > 
<  '_YG4OIIXOEeSup9fKV6290w : PCMrepositoryOperationInterface@pcmflatten | parentInterfaces@-@@-@Interface@PCMrepositoryInterface@pcmflatten : Set{mt} #
    protocols@-@@-@Interface@PCMrepositoryInterface@pcmflatten : Set{mt} # requiredCharacterisations@PCMrepositoryInterface@pcmflatten : Set{mt} #
    repository@-@@-@Interface@PCMrepositoryInterface@pcmflatten : '_dqFLECHbEd6tG9VclJz3cw #
    signatures@-@@-@OperationInterface@PCMrepositoryOperationInterface@pcmflatten : Set{'_iTDuQIXOEeSup9fKV6290w} # entityName@PCMentityNamedElement@pcmflatten :
    "BInterface" # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_YG4OIIXOEeSup9fKV6290w" > 
<  '_ZOKCcIXSEeSup9fKV6290w : PCMallocationAllocationContext@pcmflatten | resourceContainer@-@AllocationContext@PCMallocationAllocationContext@pcmflatten :
    '_B0aZ0CHdEd6lJo4DCALHMw # assemblyContext@-@AllocationContext@PCMallocationAllocationContext@pcmflatten : '_E17P8IXQEeSup9fKV6290w #
    allocation@-@AllocationContext@PCMallocationAllocationContext@pcmflatten : '_JiPBICHdEd6lJo4DCALHMw #
    eventChannel@-@@-@AllocationContext@PCMallocationAllocationContext@pcmflatten : null # entityName@PCMentityNamedElement@pcmflatten :
    "Allocation_Assembly_BComponent <BComponent> <BComponent>" # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_ZOKCcIXSEeSup9fKV6290w" > 
<  '__VHF0CHcEd6lJo4DCALHMw : PCMcompositionProvidedDelegationConnector@pcmflatten | parentStructure@-@@-@Connector@PCMcompositionConnector@pcmflatten :
    '_84D0kCHcEd6lJo4DCALHMw # innerProvidedRole@-@ProvidedDelegationConnector@PCMcompositionProvidedDelegationConnector@pcmflatten : '_qZKs0CHbEd62GabW1zGSBw #
    outerProvidedRole@-@ProvidedDelegationConnector@PCMcompositionProvidedDelegationConnector@pcmflatten : '_-r1fUCHcEd6lJo4DCALHMw #
    assemblyContext@-@ProvidedDelegationConnector@PCMcompositionProvidedDelegationConnector@pcmflatten : '_9c3KwCHcEd6lJo4DCALHMw #
    entityName@PCMentityNamedElement@pcmflatten : "ProvDelegation Provided_AnInterface -> Provided_AnInterface_AComponent" #
    id@IDENTIFIERidentifierIdentifier@pcmflatten : "__VHF0CHcEd6lJo4DCALHMw" > 
<  '_dqFLECHbEd6tG9VclJz3cw : PCMrepositoryRepository@pcmflatten | components@-@@-@Repository@PCMrepositoryRepository@pcmflatten : Set{'_Rv0lcIXOEeSup9fKV6290w ;
    '_os1t4CHbEd62GabW1zGSBw} # interfaces@-@@-@Repository@PCMrepositoryRepository@pcmflatten : Set{'_YG4OIIXOEeSup9fKV6290w ; '_n7g-oCHbEd62GabW1zGSBw} #
    failureTypes@-@@-@Repository@PCMrepositoryRepository@pcmflatten : Set{mt} # dataTypes@-@@-@Repository@PCMrepositoryRepository@pcmflatten : Set{mt} #
    entityName@PCMentityNamedElement@pcmflatten : "defaultRepository" # repositoryDescription@PCMrepositoryRepository@pcmflatten : null #
    id@IDENTIFIERidentifierIdentifier@pcmflatten : "_dqFLECHbEd6tG9VclJz3cw" > 
<  '_gJ_TgIXPEeSup9fKV6290w : PCMseffLoopAction@pcmflatten | resourceDemand@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} #
    infrastructureCall@-@@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} #
    resourceCall@-@@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} # predecessor@-@AbstractAction@PCMseffAbstractAction@pcmflatten :
    '_mHkhsIXOEeSup9fKV6290w # successor@-@AbstractAction@PCMseffAbstractAction@pcmflatten : '_tfxzcIXQEeSup9fKV6290w #
    resourceDemandingBehaviour@-@AbstractAction@PCMseffAbstractAction@pcmflatten : '_mHj6oIXOEeSup9fKV6290w # token@PCMseffAbstractAction@pcmflatten : OrderedSet{
    mt-ord} # bodyBehaviour@-@Loop@PCMseffAbstractLoopAction@pcmflatten : '_gKDk8IXPEeSup9fKV6290w # iterationCount@-@LoopAction@PCMseffLoopAction@pcmflatten :
    '/4/@components__Repository.1/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.2/@iterationCount_LoopAction #
    entityName@PCMentityNamedElement@pcmflatten : "aName" # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_gJ_TgIXPEeSup9fKV6290w" > 
<  '_gKDk8IXPEeSup9fKV6290w : PCMseffResourceDemandingBehaviour@pcmflatten |
    abstractLoopAction@-@ResourceDemandingBehaviour@PCMseffResourceDemandingBehaviour@pcmflatten : '_gJ_TgIXPEeSup9fKV6290w #
    abstractBranchTransition@-@ResourceDemandingBehaviour@PCMseffResourceDemandingBehaviour@pcmflatten : null #
    steps@-@Behaviour@PCMseffResourceDemandingBehaviour@pcmflatten : Set{'_gKEzEIXPEeSup9fKV6290w ; '_gKEzEYXPEeSup9fKV6290w ; '_xomfcIXPEeSup9fKV6290w} #
    tpOb@PCMseffResourceDemandingBehaviour@pcmflatten : null # rtOb@PCMseffResourceDemandingBehaviour@pcmflatten : null #
    id@IDENTIFIERidentifierIdentifier@pcmflatten : "_gKDk8IXPEeSup9fKV6290w" > 
<  '_gKEzEIXPEeSup9fKV6290w : PCMseffStartAction@pcmflatten | resourceDemand@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} #
    infrastructureCall@-@@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} #
    resourceCall@-@@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} # predecessor@-@AbstractAction@PCMseffAbstractAction@pcmflatten : null #
    successor@-@AbstractAction@PCMseffAbstractAction@pcmflatten : '_xomfcIXPEeSup9fKV6290w #
    resourceDemandingBehaviour@-@AbstractAction@PCMseffAbstractAction@pcmflatten : '_gKDk8IXPEeSup9fKV6290w # token@PCMseffAbstractAction@pcmflatten : OrderedSet{
    mt-ord} # entityName@PCMentityNamedElement@pcmflatten : "aName" # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_gKEzEIXPEeSup9fKV6290w" > 
<  '_gKEzEYXPEeSup9fKV6290w : PCMseffStopAction@pcmflatten | resourceDemand@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} #
    infrastructureCall@-@@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} #
    resourceCall@-@@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} # predecessor@-@AbstractAction@PCMseffAbstractAction@pcmflatten :
    '_xomfcIXPEeSup9fKV6290w # successor@-@AbstractAction@PCMseffAbstractAction@pcmflatten : null #
    resourceDemandingBehaviour@-@AbstractAction@PCMseffAbstractAction@pcmflatten : '_gKDk8IXPEeSup9fKV6290w # token@PCMseffAbstractAction@pcmflatten : OrderedSet{
    mt-ord} # entityName@PCMentityNamedElement@pcmflatten : "aName" # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_gKEzEYXPEeSup9fKV6290w" > 
<  '_iTDuQIXOEeSup9fKV6290w : PCMrepositoryOperationSignature@pcmflatten | exceptions@-@@-@Signature@PCMrepositorySignature@pcmflatten : Set{mt} #
    failureType@PCMrepositorySignature@pcmflatten : Set{mt} # interface@-@@-@OperationSignature@PCMrepositoryOperationSignature@pcmflatten : '_YG4OIIXOEeSup9fKV6290w
    # parameters@-@@-@OperationSignature@PCMrepositoryOperationSignature@pcmflatten : OrderedSet{
    '/4/@interfaces__Repository.1/@signatures__OperationInterface.0/@parameters__OperationSignature.0} #
    returnType@-@@-@OperationSignature@PCMrepositoryOperationSignature@pcmflatten : '/3/@dataTypes__Repository.0 # entityName@PCMentityNamedElement@pcmflatten : "fo"
    # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_iTDuQIXOEeSup9fKV6290w" > 
<  '_mHheYIXOEeSup9fKV6290w : PCMrepositoryOperationProvidedRole@pcmflatten | providingEntity@-@ProvidedRole@PCMrepositoryProvidedRole@pcmflatten :
    '_Rv0lcIXOEeSup9fKV6290w # providedInterface@-@@-@OperationProvidedRole@PCMrepositoryOperationProvidedRole@pcmflatten : '_YG4OIIXOEeSup9fKV6290w #
    entityName@PCMentityNamedElement@pcmflatten : "Provided_BInterface_BComponent" # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_mHheYIXOEeSup9fKV6290w" > 
<  '_mHj6oIXOEeSup9fKV6290w : PCMseffResourceDemandingSEFF@pcmflatten | abstractLoopAction@-@ResourceDemandingBehaviour@PCMseffResourceDemandingBehaviour@pcmflatten
    : null # abstractBranchTransition@-@ResourceDemandingBehaviour@PCMseffResourceDemandingBehaviour@pcmflatten : null #
    steps@-@Behaviour@PCMseffResourceDemandingBehaviour@pcmflatten : Set{'_gJ_TgIXPEeSup9fKV6290w ; '_mHkhsIXOEeSup9fKV6290w ; '_mHkhsYXOEeSup9fKV6290w ;
    '_tfxzcIXQEeSup9fKV6290w} # tpOb@PCMseffResourceDemandingBehaviour@pcmflatten : null # rtOb@PCMseffResourceDemandingBehaviour@pcmflatten : null #
    describedService@-@@-@SEFF@PCMseffServiceEffectSpecification@pcmflatten : '_iTDuQIXOEeSup9fKV6290w #
    basicComponent@-@ServiceEffectSpecification@PCMseffServiceEffectSpecification@pcmflatten : '_Rv0lcIXOEeSup9fKV6290w #
    resourceDemandingInternalBehaviours@PCMseffResourceDemandingSEFF@pcmflatten : Set{mt} # seffTypeID@PCMseffServiceEffectSpecification@pcmflatten : "1" #
    id@IDENTIFIERidentifierIdentifier@pcmflatten : "_mHj6oIXOEeSup9fKV6290w" > 
<  '_mHkhsIXOEeSup9fKV6290w : PCMseffStartAction@pcmflatten | resourceDemand@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} #
    infrastructureCall@-@@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} #
    resourceCall@-@@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} # predecessor@-@AbstractAction@PCMseffAbstractAction@pcmflatten : null #
    successor@-@AbstractAction@PCMseffAbstractAction@pcmflatten : '_gJ_TgIXPEeSup9fKV6290w #
    resourceDemandingBehaviour@-@AbstractAction@PCMseffAbstractAction@pcmflatten : '_mHj6oIXOEeSup9fKV6290w # token@PCMseffAbstractAction@pcmflatten : OrderedSet{
    mt-ord} # entityName@PCMentityNamedElement@pcmflatten : "start" # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_mHkhsIXOEeSup9fKV6290w" > 
<  '_mHkhsYXOEeSup9fKV6290w : PCMseffStopAction@pcmflatten | resourceDemand@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} #
    infrastructureCall@-@@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} #
    resourceCall@-@@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} # predecessor@-@AbstractAction@PCMseffAbstractAction@pcmflatten :
    '_tfxzcIXQEeSup9fKV6290w # successor@-@AbstractAction@PCMseffAbstractAction@pcmflatten : null #
    resourceDemandingBehaviour@-@AbstractAction@PCMseffAbstractAction@pcmflatten : '_mHj6oIXOEeSup9fKV6290w # token@PCMseffAbstractAction@pcmflatten : OrderedSet{
    mt-ord} # entityName@PCMentityNamedElement@pcmflatten : "stop" # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_mHkhsYXOEeSup9fKV6290w" > 
<  '_n7g-oCHbEd62GabW1zGSBw : PCMrepositoryOperationInterface@pcmflatten | parentInterfaces@-@@-@Interface@PCMrepositoryInterface@pcmflatten : Set{mt} #
    protocols@-@@-@Interface@PCMrepositoryInterface@pcmflatten : Set{mt} # requiredCharacterisations@PCMrepositoryInterface@pcmflatten : Set{mt} #
    repository@-@@-@Interface@PCMrepositoryInterface@pcmflatten : '_dqFLECHbEd6tG9VclJz3cw #
    signatures@-@@-@OperationInterface@PCMrepositoryOperationInterface@pcmflatten : Set{'_KjhikgzkEeCFg86gxKwVPw} # entityName@PCMentityNamedElement@pcmflatten :
    "AInterface" # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_n7g-oCHbEd62GabW1zGSBw" > 
<  '_nvHX4KkREdyEA_b89s7q9w : PCMresourcetypeProcessingResourceType@pcmflatten |
    resourceProvidedRoles@-@@-@ResourceInterfaceProvidingEntity@PCMentityResourceInterfaceProvidingEntity@pcmflatten : Set{'_x68UoE5dEeCg1tUg4V9tRw} #
    hardwareInducedFailureType@-@@-@ProcessingResourceType@PCMresourcetypeProcessingResourceType@pcmflatten : null #
    resourceRepository@-@ResourceType@PCMresourcetypeResourceType@pcmflatten : '/1 # unit@UNITSunitsUnitCarryingElement@pcmflatten : null #
    entityName@PCMentityNamedElement@pcmflatten : "DELAY" # unitSpecification@UNITSunitsUnitCarryingElement@pcmflatten : "seconds" #
    id@IDENTIFIERidentifierIdentifier@pcmflatten : "_nvHX4KkREdyEA_b89s7q9w" > 
<  '_o3sScH2AEdyH8uerKnHYug : PCMresourcetypeCommunicationLinkResourceType@pcmflatten |
    resourceProvidedRoles@-@@-@ResourceInterfaceProvidingEntity@PCMentityResourceInterfaceProvidingEntity@pcmflatten : Set{mt} #
    resourceRepository@-@ResourceType@PCMresourcetypeResourceType@pcmflatten : '/1 #
    networkInducedFailureType@-@@-@CommunicationLinkResourceType@PCMresourcetypeCommunicationLinkResourceType@pcmflatten : null #
    unit@UNITSunitsUnitCarryingElement@pcmflatten : null # entityName@PCMentityNamedElement@pcmflatten : "LAN" #
    unitSpecification@UNITSunitsUnitCarryingElement@pcmflatten : "byte per second" # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_o3sScH2AEdyH8uerKnHYug" > 
<  '_oKe0oIXOEeSup9fKV6290w : PCMrepositoryOperationRequiredRole@pcmflatten | requiringEntity@-@RequiredRole@PCMrepositoryRequiredRole@pcmflatten :
    '_os1t4CHbEd62GabW1zGSBw # requiredInterface@-@@-@OperationRequiredRole@PCMrepositoryOperationRequiredRole@pcmflatten : '_YG4OIIXOEeSup9fKV6290w #
    entityName@PCMentityNamedElement@pcmflatten : "Required_BInterface_AComponent" # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_oKe0oIXOEeSup9fKV6290w" > 
<  '_oro4gG3fEdy4YaaT-RYrLQ : PCMresourcetypeProcessingResourceType@pcmflatten |
    resourceProvidedRoles@-@@-@ResourceInterfaceProvidingEntity@PCMentityResourceInterfaceProvidingEntity@pcmflatten : Set{'_patY8E5dEeCg1tUg4V9tRw} #
    hardwareInducedFailureType@-@@-@ProcessingResourceType@PCMresourcetypeProcessingResourceType@pcmflatten : null #
    resourceRepository@-@ResourceType@PCMresourcetypeResourceType@pcmflatten : '/1 # unit@UNITSunitsUnitCarryingElement@pcmflatten : null #
    entityName@PCMentityNamedElement@pcmflatten : "CPU" # unitSpecification@UNITSunitsUnitCarryingElement@pcmflatten : "work units per second" #
    id@IDENTIFIERidentifierIdentifier@pcmflatten : "_oro4gG3fEdy4YaaT-RYrLQ" > 
<  '_os1t4CHbEd62GabW1zGSBw : PCMrepositoryBasicComponent@pcmflatten | providedRoles@-@InterfaceProvidingEntity@PCMentityInterfaceProvidingEntity@pcmflatten : Set{
    '_qZKs0CHbEd62GabW1zGSBw} # requiredRoles@-@InterfaceRequiringEntity@PCMentityInterfaceRequiringEntity@pcmflatten : Set{'_oKe0oIXOEeSup9fKV6290w} #
    resourceRequiredRoles@-@@-@ResourceInterfaceRequiringEntity@PCMentityResourceInterfaceRequiringEntity@pcmflatten : Set{mt} #
    serviceEffectSpecifications@-@@-@BasicComponent@PCMrepositoryBasicComponent@pcmflatten : Set{'12345} #
    passiveResource@-@BasicComponent@PCMrepositoryBasicComponent@pcmflatten : Set{mt} #
    parentCompleteComponentTypes@PCMrepositoryImplementationComponentType@pcmflatten : Set{mt} #
    componentParameterUsage@-@ImplementationComponentType@PCMrepositoryImplementationComponentType@pcmflatten : Set{mt} #
    repository@-@@-@RepositoryComponent@PCMrepositoryRepositoryComponent@pcmflatten : '_dqFLECHbEd6tG9VclJz3cw # entityName@PCMentityNamedElement@pcmflatten :
    "AComponent" # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_os1t4CHbEd62GabW1zGSBw" > 
<  '_patY8E5dEeCg1tUg4V9tRw : PCMentityResourceProvidedRole@pcmflatten |
    resourceInterfaceProvidingEntity@-@@-@ResourceProvidedRole@PCMentityResourceProvidedRole@pcmflatten : '_oro4gG3fEdy4YaaT-RYrLQ #
    providedResourceInterface@-@@-@ResourceProvidedRole@PCMentityResourceProvidedRole@pcmflatten : '_tw_Q8E5CEeCUKeckjJ_n-w #
    entityName@PCMentityNamedElement@pcmflatten : "ResourceProvidedRole_CpuInterface_CPU" # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_patY8E5dEeCg1tUg4V9tRw"
    > 
<  '_qZKs0CHbEd62GabW1zGSBw : PCMrepositoryOperationProvidedRole@pcmflatten | providingEntity@-@ProvidedRole@PCMrepositoryProvidedRole@pcmflatten :
    '_os1t4CHbEd62GabW1zGSBw # providedInterface@-@@-@OperationProvidedRole@PCMrepositoryOperationProvidedRole@pcmflatten : '_n7g-oCHbEd62GabW1zGSBw #
    entityName@PCMentityNamedElement@pcmflatten : "Provided_AnInterface_AComponent" # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_qZKs0CHbEd62GabW1zGSBw" > 
<  '_qZUd0CHbEd62GabW1zGSBw : PCMseffStartAction@pcmflatten | resourceDemand@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} #
    infrastructureCall@-@@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} #
    resourceCall@-@@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} # predecessor@-@AbstractAction@PCMseffAbstractAction@pcmflatten : null #
    successor@-@AbstractAction@PCMseffAbstractAction@pcmflatten : '_tfAiwCHjEd6ZSMvOJK-6LQ #
    resourceDemandingBehaviour@-@AbstractAction@PCMseffAbstractAction@pcmflatten : '12345 # token@PCMseffAbstractAction@pcmflatten : OrderedSet{mt-ord} #
    entityName@PCMentityNamedElement@pcmflatten : "aName" # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_qZUd0CHbEd62GabW1zGSBw" > 
<  '_qZUd0SHbEd62GabW1zGSBw : PCMseffStopAction@pcmflatten | resourceDemand@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} #
    infrastructureCall@-@@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} #
    resourceCall@-@@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} # predecessor@-@AbstractAction@PCMseffAbstractAction@pcmflatten :
    '_tfAiwCHjEd6ZSMvOJK-6LQ # successor@-@AbstractAction@PCMseffAbstractAction@pcmflatten : null #
    resourceDemandingBehaviour@-@AbstractAction@PCMseffAbstractAction@pcmflatten : '12345 # token@PCMseffAbstractAction@pcmflatten : OrderedSet{mt-ord} #
    entityName@PCMentityNamedElement@pcmflatten : "aName" # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_qZUd0SHbEd62GabW1zGSBw" > 
<  '_rl6MwCHbEd62GabW1zGSBw : PCMseffInternalAction@pcmflatten | resourceDemand@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{'/4/@components__Repository.0/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.2/@branches_Branch.0/@branchBehaviour_BranchTransition/@steps_Behaviour.2/@resourceDemand_Action.0} # infrastructureCall@-@@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} #
    resourceCall@-@@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} # predecessor@-@AbstractAction@PCMseffAbstractAction@pcmflatten :
    '_vN34USHjEd6ZSMvOJK-6LQ # successor@-@AbstractAction@PCMseffAbstractAction@pcmflatten : '_VloHcIXQEeSup9fKV6290w #
    resourceDemandingBehaviour@-@AbstractAction@PCMseffAbstractAction@pcmflatten : '_ssGw84r-EeG0c6Q1F-wA1Q # token@PCMseffAbstractAction@pcmflatten : OrderedSet{
    '21} # internalFailureOccurrenceDescriptions@-@@-@InternalAction@PCMseffInternalAction@pcmflatten : Set{mt} # queue@PCMseffInternalAction@pcmflatten : Sequence{
    mt-ord} # entityName@PCMentityNamedElement@pcmflatten : "compute" # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_rl6MwCHbEd62GabW1zGSBw" > 
<  '_ssGw-Yr-EeG0c6Q1F-wA1Q : PCMseffResourceDemandingBehaviour@pcmflatten |
    abstractLoopAction@-@ResourceDemandingBehaviour@PCMseffResourceDemandingBehaviour@pcmflatten : null #
    abstractBranchTransition@-@ResourceDemandingBehaviour@PCMseffResourceDemandingBehaviour@pcmflatten : '_zcoXwCHjEd6ZSMvOJK-6LQ #
    steps@-@Behaviour@PCMseffResourceDemandingBehaviour@pcmflatten : Set{'_0eyYUCHjEd6ZSMvOJK-6LQ ; '_zcoXwSHjEd6ZSMvOJK-6LQ ; '_zcoXwiHjEd6ZSMvOJK-6LQ} #
    tpOb@PCMseffResourceDemandingBehaviour@pcmflatten : null # rtOb@PCMseffResourceDemandingBehaviour@pcmflatten : null #
    id@IDENTIFIERidentifierIdentifier@pcmflatten : "_ssGw-Yr-EeG0c6Q1F-wA1Q" > 
<  '_ssGw84r-EeG0c6Q1F-wA1Q : PCMseffResourceDemandingBehaviour@pcmflatten |
    abstractLoopAction@-@ResourceDemandingBehaviour@PCMseffResourceDemandingBehaviour@pcmflatten : null #
    abstractBranchTransition@-@ResourceDemandingBehaviour@PCMseffResourceDemandingBehaviour@pcmflatten : '_vN34UCHjEd6ZSMvOJK-6LQ #
    steps@-@Behaviour@PCMseffResourceDemandingBehaviour@pcmflatten : Set{'_VloHcIXQEeSup9fKV6290w ; '_rl6MwCHbEd62GabW1zGSBw ; '_vN34USHjEd6ZSMvOJK-6LQ ;
    '_vN34UiHjEd6ZSMvOJK-6LQ} # tpOb@PCMseffResourceDemandingBehaviour@pcmflatten : null # rtOb@PCMseffResourceDemandingBehaviour@pcmflatten : null #
    id@IDENTIFIERidentifierIdentifier@pcmflatten : "_ssGw84r-EeG0c6Q1F-wA1Q" > 
<  '_ssJ0QYr-EeG0c6Q1F-wA1Q : PCMresourceenvironmentProcessingResourceSpecification@pcmflatten |
    schedulingPolicy@PCMresourceenvironmentProcessingResourceSpecification@pcmflatten : 'ProcessorSharing #
    activeResourceType@-@ActiveResourceSpecification@PCMresourceenvironmentProcessingResourceSpecification@pcmflatten : '_oro4gG3fEdy4YaaT-RYrLQ #
    processingRate@-@ProcessingResourceSpecification@PCMresourceenvironmentProcessingResourceSpecification@pcmflatten :
    '/2/@resourceContainer_ResourceEnvironment.0/@activeResourceSpecifications_ResourceContainer.0/@processingRate_ProcessingResourceSpecification #
    resourceContainer@-@ProcessingResourceSpecification@PCMresourceenvironmentProcessingResourceSpecification@pcmflatten : '_B0aZ0CHdEd6lJo4DCALHMw #
    queue@PCMresourceenvironmentProcessingResourceSpecification@pcmflatten : Sequence{'21} # MTTR@PCMresourceenvironmentProcessingResourceSpecification@pcmflatten :
    0.0 # MTTF@PCMresourceenvironmentProcessingResourceSpecification@pcmflatten : 0.0 #
    requiredByContainer@PCMresourceenvironmentProcessingResourceSpecification@pcmflatten : false #
    numberOfReplicas@PCMresourceenvironmentProcessingResourceSpecification@pcmflatten : 1 # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_ssJ0QYr-EeG0c6Q1F-wA1Q"
    > 
<  '_tCR8kE5dEeCg1tUg4V9tRw : PCMentityResourceProvidedRole@pcmflatten |
    resourceInterfaceProvidingEntity@-@@-@ResourceProvidedRole@PCMentityResourceProvidedRole@pcmflatten : '_BIjHoQ3KEdyouMqirZIhzQ #
    providedResourceInterface@-@@-@ResourceProvidedRole@PCMentityResourceProvidedRole@pcmflatten : '_xXv8QE5CEeCUKeckjJ_n-w #
    entityName@PCMentityNamedElement@pcmflatten : "ResourceProvidedRole_HddInterface_HDD" # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_tCR8kE5dEeCg1tUg4V9tRw"
    > 
<  '_tfAiwCHjEd6ZSMvOJK-6LQ : PCMseffBranchAction@pcmflatten | resourceDemand@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} #
    infrastructureCall@-@@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} #
    resourceCall@-@@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} # predecessor@-@AbstractAction@PCMseffAbstractAction@pcmflatten :
    '_qZUd0CHbEd62GabW1zGSBw # successor@-@AbstractAction@PCMseffAbstractAction@pcmflatten : '_qZUd0SHbEd62GabW1zGSBw #
    resourceDemandingBehaviour@-@AbstractAction@PCMseffAbstractAction@pcmflatten : '12345 # token@PCMseffAbstractAction@pcmflatten : OrderedSet{mt-ord} #
    branches@-@Branch@PCMseffBranchAction@pcmflatten : OrderedSet{'_vN34UCHjEd6ZSMvOJK-6LQ # '_zcoXwCHjEd6ZSMvOJK-6LQ} # entityName@PCMentityNamedElement@pcmflatten
    : "branch" # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_tfAiwCHjEd6ZSMvOJK-6LQ" > 
<  '_tfxzcIXQEeSup9fKV6290w : PCMseffSetVariableAction@pcmflatten | resourceDemand@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} #
    infrastructureCall@-@@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} #
    resourceCall@-@@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} # predecessor@-@AbstractAction@PCMseffAbstractAction@pcmflatten :
    '_gJ_TgIXPEeSup9fKV6290w # successor@-@AbstractAction@PCMseffAbstractAction@pcmflatten : '_mHkhsYXOEeSup9fKV6290w #
    resourceDemandingBehaviour@-@AbstractAction@PCMseffAbstractAction@pcmflatten : '_mHj6oIXOEeSup9fKV6290w # token@PCMseffAbstractAction@pcmflatten : OrderedSet{
    mt-ord} # localVariableUsages@-@SetVariableAction@PCMseffSetVariableAction@pcmflatten : Set{
    '/4/@components__Repository.1/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.3/@localVariableUsages_SetVariableAction.0} #
    entityName@PCMentityNamedElement@pcmflatten : "aName" # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_tfxzcIXQEeSup9fKV6290w" > 
<  '_tw_Q8E5CEeCUKeckjJ_n-w : PCMresourcetypeResourceInterface@pcmflatten | resourceRepository@-@@-@ResourceInterface@PCMresourcetypeResourceInterface@pcmflatten :
    '/1 # resourceSignatures@-@@-@ResourceInterface@PCMresourcetypeResourceInterface@pcmflatten : Set{'_wF22kE5CEeCUKeckjJ_n-w} #
    entityName@PCMentityNamedElement@pcmflatten : "CpuInterface" # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_tw_Q8E5CEeCUKeckjJ_n-w" > 
<  '_vN34UCHjEd6ZSMvOJK-6LQ : PCMseffProbabilisticBranchTransition@pcmflatten | branchAction@-@AbstractBranchTransition@PCMseffAbstractBranchTransition@pcmflatten :
    '_tfAiwCHjEd6ZSMvOJK-6LQ # branchBehaviour@-@BranchTransition@PCMseffAbstractBranchTransition@pcmflatten : '_ssGw84r-EeG0c6Q1F-wA1Q #
    entityName@PCMentityNamedElement@pcmflatten : "aName" # branchProbability@PCMseffProbabilisticBranchTransition@pcmflatten : 1.0 #
    id@IDENTIFIERidentifierIdentifier@pcmflatten : "_vN34UCHjEd6ZSMvOJK-6LQ" > 
<  '_vN34USHjEd6ZSMvOJK-6LQ : PCMseffStartAction@pcmflatten | resourceDemand@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} #
    infrastructureCall@-@@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} #
    resourceCall@-@@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} # predecessor@-@AbstractAction@PCMseffAbstractAction@pcmflatten : null #
    successor@-@AbstractAction@PCMseffAbstractAction@pcmflatten : '_rl6MwCHbEd62GabW1zGSBw #
    resourceDemandingBehaviour@-@AbstractAction@PCMseffAbstractAction@pcmflatten : '_ssGw84r-EeG0c6Q1F-wA1Q # token@PCMseffAbstractAction@pcmflatten : OrderedSet{
    mt-ord} # entityName@PCMentityNamedElement@pcmflatten : "aName" # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_vN34USHjEd6ZSMvOJK-6LQ" > 
<  '_vN34UiHjEd6ZSMvOJK-6LQ : PCMseffStopAction@pcmflatten | resourceDemand@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} #
    infrastructureCall@-@@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} #
    resourceCall@-@@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} # predecessor@-@AbstractAction@PCMseffAbstractAction@pcmflatten :
    '_VloHcIXQEeSup9fKV6290w # successor@-@AbstractAction@PCMseffAbstractAction@pcmflatten : null #
    resourceDemandingBehaviour@-@AbstractAction@PCMseffAbstractAction@pcmflatten : '_ssGw84r-EeG0c6Q1F-wA1Q # token@PCMseffAbstractAction@pcmflatten : OrderedSet{
    mt-ord} # entityName@PCMentityNamedElement@pcmflatten : "aName" # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_vN34UiHjEd6ZSMvOJK-6LQ" > 
<  '_wF22kE5CEeCUKeckjJ_n-w : PCMresourcetypeResourceSignature@pcmflatten | parameter@-@@-@ResourceSignature@PCMresourcetypeResourceSignature@pcmflatten : null #
    resourceInterface@-@@-@ResourceSignature@PCMresourcetypeResourceSignature@pcmflatten : '_tw_Q8E5CEeCUKeckjJ_n-w # entityName@PCMentityNamedElement@pcmflatten :
    "process" # resourceServiceId@PCMresourcetypeResourceSignature@pcmflatten : 1 # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_wF22kE5CEeCUKeckjJ_n-w" > 
<  '_x68UoE5dEeCg1tUg4V9tRw : PCMentityResourceProvidedRole@pcmflatten |
    resourceInterfaceProvidingEntity@-@@-@ResourceProvidedRole@PCMentityResourceProvidedRole@pcmflatten : '_nvHX4KkREdyEA_b89s7q9w #
    providedResourceInterface@-@@-@ResourceProvidedRole@PCMentityResourceProvidedRole@pcmflatten : '_tw_Q8E5CEeCUKeckjJ_n-w #
    entityName@PCMentityNamedElement@pcmflatten : "ResourceProvidedRole_CpuInterface_DELAY" # id@IDENTIFIERidentifierIdentifier@pcmflatten :
    "_x68UoE5dEeCg1tUg4V9tRw" > 
<  '_xXv8QE5CEeCUKeckjJ_n-w : PCMresourcetypeResourceInterface@pcmflatten | resourceRepository@-@@-@ResourceInterface@PCMresourcetypeResourceInterface@pcmflatten :
    '/1 # resourceSignatures@-@@-@ResourceInterface@PCMresourcetypeResourceInterface@pcmflatten : Set{'_ygMyEE5CEeCUKeckjJ_n-w ; '_zUFtIE5CEeCUKeckjJ_n-w} #
    entityName@PCMentityNamedElement@pcmflatten : "HddInterface" # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_xXv8QE5CEeCUKeckjJ_n-w" > 
<  '_xomfcIXPEeSup9fKV6290w : PCMseffInternalAction@pcmflatten | resourceDemand@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{
    '/4/@components__Repository.1/@serviceEffectSpecifications__BasicComponent.0/@steps_Behaviour.2/@bodyBehaviour_Loop/@steps_Behaviour.2/@resourceDemand_Action.0}
    # infrastructureCall@-@@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} #
    resourceCall@-@@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} # predecessor@-@AbstractAction@PCMseffAbstractAction@pcmflatten :
    '_gKEzEIXPEeSup9fKV6290w # successor@-@AbstractAction@PCMseffAbstractAction@pcmflatten : '_gKEzEYXPEeSup9fKV6290w #
    resourceDemandingBehaviour@-@AbstractAction@PCMseffAbstractAction@pcmflatten : '_gKDk8IXPEeSup9fKV6290w # token@PCMseffAbstractAction@pcmflatten : OrderedSet{
    mt-ord} # internalFailureOccurrenceDescriptions@-@@-@InternalAction@PCMseffInternalAction@pcmflatten : Set{mt} # queue@PCMseffInternalAction@pcmflatten :
    Sequence{mt-ord} # entityName@PCMentityNamedElement@pcmflatten : "aName" # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_xomfcIXPEeSup9fKV6290w" > 
<  '_ygMyEE5CEeCUKeckjJ_n-w : PCMresourcetypeResourceSignature@pcmflatten | parameter@-@@-@ResourceSignature@PCMresourcetypeResourceSignature@pcmflatten : null #
    resourceInterface@-@@-@ResourceSignature@PCMresourcetypeResourceSignature@pcmflatten : '_xXv8QE5CEeCUKeckjJ_n-w # entityName@PCMentityNamedElement@pcmflatten :
    "read" # resourceServiceId@PCMresourcetypeResourceSignature@pcmflatten : 1 # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_ygMyEE5CEeCUKeckjJ_n-w" > 
<  '_zUFtIE5CEeCUKeckjJ_n-w : PCMresourcetypeResourceSignature@pcmflatten | parameter@-@@-@ResourceSignature@PCMresourcetypeResourceSignature@pcmflatten : null #
    resourceInterface@-@@-@ResourceSignature@PCMresourcetypeResourceSignature@pcmflatten : '_xXv8QE5CEeCUKeckjJ_n-w # entityName@PCMentityNamedElement@pcmflatten :
    "write" # resourceServiceId@PCMresourcetypeResourceSignature@pcmflatten : 2 # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_zUFtIE5CEeCUKeckjJ_n-w" > 
<  '_zcoXwCHjEd6ZSMvOJK-6LQ : PCMseffProbabilisticBranchTransition@pcmflatten | branchAction@-@AbstractBranchTransition@PCMseffAbstractBranchTransition@pcmflatten :
    '_tfAiwCHjEd6ZSMvOJK-6LQ # branchBehaviour@-@BranchTransition@PCMseffAbstractBranchTransition@pcmflatten : '_ssGw-Yr-EeG0c6Q1F-wA1Q #
    entityName@PCMentityNamedElement@pcmflatten : "aName" # branchProbability@PCMseffProbabilisticBranchTransition@pcmflatten : 0.0 #
    id@IDENTIFIERidentifierIdentifier@pcmflatten : "_zcoXwCHjEd6ZSMvOJK-6LQ" > 
<  '_zcoXwSHjEd6ZSMvOJK-6LQ : PCMseffStartAction@pcmflatten | resourceDemand@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} #
    infrastructureCall@-@@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} #
    resourceCall@-@@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} # predecessor@-@AbstractAction@PCMseffAbstractAction@pcmflatten : null #
    successor@-@AbstractAction@PCMseffAbstractAction@pcmflatten : '_0eyYUCHjEd6ZSMvOJK-6LQ #
    resourceDemandingBehaviour@-@AbstractAction@PCMseffAbstractAction@pcmflatten : '_ssGw-Yr-EeG0c6Q1F-wA1Q # token@PCMseffAbstractAction@pcmflatten : OrderedSet{
    mt-ord} # entityName@PCMentityNamedElement@pcmflatten : "aName" # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_zcoXwSHjEd6ZSMvOJK-6LQ" > 
<  '_zcoXwiHjEd6ZSMvOJK-6LQ : PCMseffStopAction@pcmflatten | resourceDemand@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} #
    infrastructureCall@-@@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} #
    resourceCall@-@@-@Action@PCMseffAbstractInternalControlFlowAction@pcmflatten : Set{mt} # predecessor@-@AbstractAction@PCMseffAbstractAction@pcmflatten :
    '_0eyYUCHjEd6ZSMvOJK-6LQ # successor@-@AbstractAction@PCMseffAbstractAction@pcmflatten : null #
    resourceDemandingBehaviour@-@AbstractAction@PCMseffAbstractAction@pcmflatten : '_ssGw-Yr-EeG0c6Q1F-wA1Q # token@PCMseffAbstractAction@pcmflatten : OrderedSet{
    mt-ord} # entityName@PCMentityNamedElement@pcmflatten : "aName" # id@IDENTIFIERidentifierIdentifier@pcmflatten : "_zcoXwiHjEd6ZSMvOJK-6LQ" > 
<  'clk@ : Clock@MGBehavior | time@Clock@MGBehavior : 500 > 
<  'ids@ : Counter@MGBehavior | value@Counter@MGBehavior : 68 > 
<  'rdm@ : Counter@MGBehavior | value@Counter@MGBehavior : 70 >}) .